// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOne.Client;

namespace TalonOne.Model
{
    /// <summary>
    /// AdditionalCampaignProperties
    /// </summary>
    public partial class AdditionalCampaignProperties : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalCampaignProperties" /> class.
        /// </summary>
        /// <param name="frontendState">The campaign state displayed in the Campaign Manager.</param>
        /// <param name="storesImported">Indicates whether the linked stores were imported via a CSV file.</param>
        /// <param name="budgets">A list of all the budgets that are defined by this campaign and their usage.  **Note:** Budgets that are not defined do not appear in this list and their usage is not counted until they are defined. </param>
        /// <param name="couponRedemptionCount">This property is **deprecated**. The count should be available under *budgets* property. Number of coupons redeemed in the campaign. </param>
        /// <param name="referralRedemptionCount">This property is **deprecated**. The count should be available under *budgets* property. Number of referral codes redeemed in the campaign. </param>
        /// <param name="discountCount">This property is **deprecated**. The count should be available under *budgets* property. Total amount of discounts redeemed in the campaign. </param>
        /// <param name="discountEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of times discounts were redeemed in this campaign. </param>
        /// <param name="couponCreationCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of coupons created by rules in this campaign. </param>
        /// <param name="customEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of custom effects triggered by rules in this campaign. </param>
        /// <param name="referralCreationCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of referrals created by rules in this campaign. </param>
        /// <param name="addFreeItemEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of times the [add free item effect](https://docs.talon.one/docs/dev/integration-api/api-effects#addfreeitem) can be triggered in this campaign. </param>
        /// <param name="awardedGiveawaysCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of giveaways awarded by rules in this campaign. </param>
        /// <param name="createdLoyaltyPointsCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points created by rules in this campaign. </param>
        /// <param name="createdLoyaltyPointsEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point creation effects triggered by rules in this campaign. </param>
        /// <param name="redeemedLoyaltyPointsCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points redeemed by rules in this campaign. </param>
        /// <param name="redeemedLoyaltyPointsEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point redemption effects triggered by rules in this campaign. </param>
        /// <param name="callApiEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of webhooks triggered by rules in this campaign. </param>
        /// <param name="reservecouponEffectCount">This property is **deprecated**. The count should be available under *budgets* property. Total number of reserve coupon effects triggered by rules in this campaign. </param>
        /// <param name="lastActivity">Timestamp of the most recent event received by this campaign.</param>
        /// <param name="updated">Timestamp of the most recent update to the campaign&#39;s property. Updates to external entities used in this campaign are **not** registered by this property, such as collection or coupon updates. </param>
        /// <param name="createdBy">Name of the user who created this campaign if available.</param>
        /// <param name="updatedBy">Name of the user who last updated this campaign if available.</param>
        /// <param name="templateId">The ID of the Campaign Template this Campaign was created from.</param>
        /// <param name="valueMapsIds">A list of value map IDs for the campaign.</param>
        [JsonConstructor]
        public AdditionalCampaignProperties(FrontendStateEnum frontendState, bool storesImported, Option<List<CampaignBudget>> budgets = default, Option<long?> couponRedemptionCount = default, Option<long?> referralRedemptionCount = default, Option<decimal?> discountCount = default, Option<long?> discountEffectCount = default, Option<long?> couponCreationCount = default, Option<long?> customEffectCount = default, Option<long?> referralCreationCount = default, Option<long?> addFreeItemEffectCount = default, Option<long?> awardedGiveawaysCount = default, Option<decimal?> createdLoyaltyPointsCount = default, Option<long?> createdLoyaltyPointsEffectCount = default, Option<decimal?> redeemedLoyaltyPointsCount = default, Option<long?> redeemedLoyaltyPointsEffectCount = default, Option<long?> callApiEffectCount = default, Option<long?> reservecouponEffectCount = default, Option<DateTime?> lastActivity = default, Option<DateTime?> updated = default, Option<string> createdBy = default, Option<string> updatedBy = default, Option<long?> templateId = default, Option<List<long>> valueMapsIds = default)
        {
            FrontendState = frontendState;
            StoresImported = storesImported;
            BudgetsOption = budgets;
            CouponRedemptionCountOption = couponRedemptionCount;
            ReferralRedemptionCountOption = referralRedemptionCount;
            DiscountCountOption = discountCount;
            DiscountEffectCountOption = discountEffectCount;
            CouponCreationCountOption = couponCreationCount;
            CustomEffectCountOption = customEffectCount;
            ReferralCreationCountOption = referralCreationCount;
            AddFreeItemEffectCountOption = addFreeItemEffectCount;
            AwardedGiveawaysCountOption = awardedGiveawaysCount;
            CreatedLoyaltyPointsCountOption = createdLoyaltyPointsCount;
            CreatedLoyaltyPointsEffectCountOption = createdLoyaltyPointsEffectCount;
            RedeemedLoyaltyPointsCountOption = redeemedLoyaltyPointsCount;
            RedeemedLoyaltyPointsEffectCountOption = redeemedLoyaltyPointsEffectCount;
            CallApiEffectCountOption = callApiEffectCount;
            ReservecouponEffectCountOption = reservecouponEffectCount;
            LastActivityOption = lastActivity;
            UpdatedOption = updated;
            CreatedByOption = createdBy;
            UpdatedByOption = updatedBy;
            TemplateIdOption = templateId;
            ValueMapsIdsOption = valueMapsIds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The campaign state displayed in the Campaign Manager.
        /// </summary>
        /// <value>The campaign state displayed in the Campaign Manager.</value>
        public enum FrontendStateEnum
        {
            /// <summary>
            /// Enum Expired for value: expired
            /// </summary>
            Expired = 1,

            /// <summary>
            /// Enum Scheduled for value: scheduled
            /// </summary>
            Scheduled = 2,

            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            Running = 3,

            /// <summary>
            /// Enum Disabled for value: disabled
            /// </summary>
            Disabled = 4,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            Archived = 5,

            /// <summary>
            /// Enum Staged for value: staged
            /// </summary>
            Staged = 6
        }

        /// <summary>
        /// Returns a <see cref="FrontendStateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FrontendStateEnum FrontendStateEnumFromString(string value)
        {
            if (value.Equals("expired"))
                return FrontendStateEnum.Expired;

            if (value.Equals("scheduled"))
                return FrontendStateEnum.Scheduled;

            if (value.Equals("running"))
                return FrontendStateEnum.Running;

            if (value.Equals("disabled"))
                return FrontendStateEnum.Disabled;

            if (value.Equals("archived"))
                return FrontendStateEnum.Archived;

            if (value.Equals("staged"))
                return FrontendStateEnum.Staged;

            throw new NotImplementedException($"Could not convert value to type FrontendStateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FrontendStateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FrontendStateEnum? FrontendStateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("expired"))
                return FrontendStateEnum.Expired;

            if (value.Equals("scheduled"))
                return FrontendStateEnum.Scheduled;

            if (value.Equals("running"))
                return FrontendStateEnum.Running;

            if (value.Equals("disabled"))
                return FrontendStateEnum.Disabled;

            if (value.Equals("archived"))
                return FrontendStateEnum.Archived;

            if (value.Equals("staged"))
                return FrontendStateEnum.Staged;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FrontendStateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FrontendStateEnumToJsonValue(FrontendStateEnum value)
        {
            if (value == FrontendStateEnum.Expired)
                return "expired";

            if (value == FrontendStateEnum.Scheduled)
                return "scheduled";

            if (value == FrontendStateEnum.Running)
                return "running";

            if (value == FrontendStateEnum.Disabled)
                return "disabled";

            if (value == FrontendStateEnum.Archived)
                return "archived";

            if (value == FrontendStateEnum.Staged)
                return "staged";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The campaign state displayed in the Campaign Manager.
        /// </summary>
        /// <value>The campaign state displayed in the Campaign Manager.</value>
        /* <example>running</example> */
        [JsonPropertyName("frontendState")]
        public FrontendStateEnum FrontendState { get; set; }

        /// <summary>
        /// Indicates whether the linked stores were imported via a CSV file.
        /// </summary>
        /// <value>Indicates whether the linked stores were imported via a CSV file.</value>
        /* <example>true</example> */
        [JsonPropertyName("storesImported")]
        public bool StoresImported { get; set; }

        /// <summary>
        /// Used to track the state of Budgets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CampaignBudget>> BudgetsOption { get; private set; }

        /// <summary>
        /// A list of all the budgets that are defined by this campaign and their usage.  **Note:** Budgets that are not defined do not appear in this list and their usage is not counted until they are defined. 
        /// </summary>
        /// <value>A list of all the budgets that are defined by this campaign and their usage.  **Note:** Budgets that are not defined do not appear in this list and their usage is not counted until they are defined. </value>
        [JsonPropertyName("budgets")]
        public List<CampaignBudget> Budgets { get { return this.BudgetsOption; } set { this.BudgetsOption = new Option<List<CampaignBudget>>(value); } }

        /// <summary>
        /// Used to track the state of CouponRedemptionCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CouponRedemptionCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Number of coupons redeemed in the campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Number of coupons redeemed in the campaign. </value>
        /* <example>163</example> */
        [JsonPropertyName("couponRedemptionCount")]
        public long? CouponRedemptionCount { get { return this.CouponRedemptionCountOption; } set { this.CouponRedemptionCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ReferralRedemptionCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ReferralRedemptionCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Number of referral codes redeemed in the campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Number of referral codes redeemed in the campaign. </value>
        /* <example>3</example> */
        [JsonPropertyName("referralRedemptionCount")]
        public long? ReferralRedemptionCount { get { return this.ReferralRedemptionCountOption; } set { this.ReferralRedemptionCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of DiscountCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> DiscountCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total amount of discounts redeemed in the campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total amount of discounts redeemed in the campaign. </value>
        /* <example>288</example> */
        [JsonPropertyName("discountCount")]
        public decimal? DiscountCount { get { return this.DiscountCountOption; } set { this.DiscountCountOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of DiscountEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> DiscountEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of times discounts were redeemed in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of times discounts were redeemed in this campaign. </value>
        /* <example>343</example> */
        [JsonPropertyName("discountEffectCount")]
        public long? DiscountEffectCount { get { return this.DiscountEffectCountOption; } set { this.DiscountEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of CouponCreationCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CouponCreationCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of coupons created by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of coupons created by rules in this campaign. </value>
        /* <example>16</example> */
        [JsonPropertyName("couponCreationCount")]
        public long? CouponCreationCount { get { return this.CouponCreationCountOption; } set { this.CouponCreationCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of CustomEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CustomEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of custom effects triggered by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of custom effects triggered by rules in this campaign. </value>
        /* <example>0</example> */
        [JsonPropertyName("customEffectCount")]
        public long? CustomEffectCount { get { return this.CustomEffectCountOption; } set { this.CustomEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ReferralCreationCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ReferralCreationCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of referrals created by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of referrals created by rules in this campaign. </value>
        /* <example>8</example> */
        [JsonPropertyName("referralCreationCount")]
        public long? ReferralCreationCount { get { return this.ReferralCreationCountOption; } set { this.ReferralCreationCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of AddFreeItemEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> AddFreeItemEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of times the [add free item effect](https://docs.talon.one/docs/dev/integration-api/api-effects#addfreeitem) can be triggered in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of times the [add free item effect](https://docs.talon.one/docs/dev/integration-api/api-effects#addfreeitem) can be triggered in this campaign. </value>
        /* <example>0</example> */
        [JsonPropertyName("addFreeItemEffectCount")]
        public long? AddFreeItemEffectCount { get { return this.AddFreeItemEffectCountOption; } set { this.AddFreeItemEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of AwardedGiveawaysCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> AwardedGiveawaysCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of giveaways awarded by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of giveaways awarded by rules in this campaign. </value>
        /* <example>9</example> */
        [JsonPropertyName("awardedGiveawaysCount")]
        public long? AwardedGiveawaysCount { get { return this.AwardedGiveawaysCountOption; } set { this.AwardedGiveawaysCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedLoyaltyPointsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CreatedLoyaltyPointsCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points created by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points created by rules in this campaign. </value>
        /* <example>9</example> */
        [JsonPropertyName("createdLoyaltyPointsCount")]
        public decimal? CreatedLoyaltyPointsCount { get { return this.CreatedLoyaltyPointsCountOption; } set { this.CreatedLoyaltyPointsCountOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedLoyaltyPointsEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CreatedLoyaltyPointsEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point creation effects triggered by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point creation effects triggered by rules in this campaign. </value>
        /* <example>2</example> */
        [JsonPropertyName("createdLoyaltyPointsEffectCount")]
        public long? CreatedLoyaltyPointsEffectCount { get { return this.CreatedLoyaltyPointsEffectCountOption; } set { this.CreatedLoyaltyPointsEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of RedeemedLoyaltyPointsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> RedeemedLoyaltyPointsCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points redeemed by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points redeemed by rules in this campaign. </value>
        /* <example>8</example> */
        [JsonPropertyName("redeemedLoyaltyPointsCount")]
        public decimal? RedeemedLoyaltyPointsCount { get { return this.RedeemedLoyaltyPointsCountOption; } set { this.RedeemedLoyaltyPointsCountOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of RedeemedLoyaltyPointsEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> RedeemedLoyaltyPointsEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point redemption effects triggered by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point redemption effects triggered by rules in this campaign. </value>
        /* <example>9</example> */
        [JsonPropertyName("redeemedLoyaltyPointsEffectCount")]
        public long? RedeemedLoyaltyPointsEffectCount { get { return this.RedeemedLoyaltyPointsEffectCountOption; } set { this.RedeemedLoyaltyPointsEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of CallApiEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CallApiEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of webhooks triggered by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of webhooks triggered by rules in this campaign. </value>
        /* <example>0</example> */
        [JsonPropertyName("callApiEffectCount")]
        public long? CallApiEffectCount { get { return this.CallApiEffectCountOption; } set { this.CallApiEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ReservecouponEffectCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ReservecouponEffectCountOption { get; private set; }

        /// <summary>
        /// This property is **deprecated**. The count should be available under *budgets* property. Total number of reserve coupon effects triggered by rules in this campaign. 
        /// </summary>
        /// <value>This property is **deprecated**. The count should be available under *budgets* property. Total number of reserve coupon effects triggered by rules in this campaign. </value>
        /* <example>9</example> */
        [JsonPropertyName("reservecouponEffectCount")]
        public long? ReservecouponEffectCount { get { return this.ReservecouponEffectCountOption; } set { this.ReservecouponEffectCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of LastActivity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastActivityOption { get; private set; }

        /// <summary>
        /// Timestamp of the most recent event received by this campaign.
        /// </summary>
        /// <value>Timestamp of the most recent event received by this campaign.</value>
        /* <example>2022-11-10T23:00:00Z</example> */
        [JsonPropertyName("lastActivity")]
        public DateTime? LastActivity { get { return this.LastActivityOption; } set { this.LastActivityOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of Updated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedOption { get; private set; }

        /// <summary>
        /// Timestamp of the most recent update to the campaign&#39;s property. Updates to external entities used in this campaign are **not** registered by this property, such as collection or coupon updates. 
        /// </summary>
        /// <value>Timestamp of the most recent update to the campaign&#39;s property. Updates to external entities used in this campaign are **not** registered by this property, such as collection or coupon updates. </value>
        /* <example>2022-10-97T35:00:00Z</example> */
        [JsonPropertyName("updated")]
        public DateTime? Updated { get { return this.UpdatedOption; } set { this.UpdatedOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CreatedByOption { get; private set; }

        /// <summary>
        /// Name of the user who created this campaign if available.
        /// </summary>
        /// <value>Name of the user who created this campaign if available.</value>
        /* <example>John Doe</example> */
        [JsonPropertyName("createdBy")]
        public string CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of UpdatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UpdatedByOption { get; private set; }

        /// <summary>
        /// Name of the user who last updated this campaign if available.
        /// </summary>
        /// <value>Name of the user who last updated this campaign if available.</value>
        /* <example>Jane Doe</example> */
        [JsonPropertyName("updatedBy")]
        public string UpdatedBy { get { return this.UpdatedByOption; } set { this.UpdatedByOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> TemplateIdOption { get; private set; }

        /// <summary>
        /// The ID of the Campaign Template this Campaign was created from.
        /// </summary>
        /// <value>The ID of the Campaign Template this Campaign was created from.</value>
        /* <example>3</example> */
        [JsonPropertyName("templateId")]
        public long? TemplateId { get { return this.TemplateIdOption; } set { this.TemplateIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ValueMapsIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>> ValueMapsIdsOption { get; private set; }

        /// <summary>
        /// A list of value map IDs for the campaign.
        /// </summary>
        /// <value>A list of value map IDs for the campaign.</value>
        /* <example>[100, 215]</example> */
        [JsonPropertyName("valueMapsIds")]
        public List<long> ValueMapsIds { get { return this.ValueMapsIdsOption; } set { this.ValueMapsIdsOption = new Option<List<long>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdditionalCampaignProperties {\n");
            sb.Append("  FrontendState: ").Append(FrontendState).Append("\n");
            sb.Append("  StoresImported: ").Append(StoresImported).Append("\n");
            sb.Append("  Budgets: ").Append(Budgets).Append("\n");
            sb.Append("  CouponRedemptionCount: ").Append(CouponRedemptionCount).Append("\n");
            sb.Append("  ReferralRedemptionCount: ").Append(ReferralRedemptionCount).Append("\n");
            sb.Append("  DiscountCount: ").Append(DiscountCount).Append("\n");
            sb.Append("  DiscountEffectCount: ").Append(DiscountEffectCount).Append("\n");
            sb.Append("  CouponCreationCount: ").Append(CouponCreationCount).Append("\n");
            sb.Append("  CustomEffectCount: ").Append(CustomEffectCount).Append("\n");
            sb.Append("  ReferralCreationCount: ").Append(ReferralCreationCount).Append("\n");
            sb.Append("  AddFreeItemEffectCount: ").Append(AddFreeItemEffectCount).Append("\n");
            sb.Append("  AwardedGiveawaysCount: ").Append(AwardedGiveawaysCount).Append("\n");
            sb.Append("  CreatedLoyaltyPointsCount: ").Append(CreatedLoyaltyPointsCount).Append("\n");
            sb.Append("  CreatedLoyaltyPointsEffectCount: ").Append(CreatedLoyaltyPointsEffectCount).Append("\n");
            sb.Append("  RedeemedLoyaltyPointsCount: ").Append(RedeemedLoyaltyPointsCount).Append("\n");
            sb.Append("  RedeemedLoyaltyPointsEffectCount: ").Append(RedeemedLoyaltyPointsEffectCount).Append("\n");
            sb.Append("  CallApiEffectCount: ").Append(CallApiEffectCount).Append("\n");
            sb.Append("  ReservecouponEffectCount: ").Append(ReservecouponEffectCount).Append("\n");
            sb.Append("  LastActivity: ").Append(LastActivity).Append("\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  ValueMapsIds: ").Append(ValueMapsIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AdditionalCampaignProperties" />
    /// </summary>
    public class AdditionalCampaignPropertiesJsonConverter : JsonConverter<AdditionalCampaignProperties>
    {
        /// <summary>
        /// The format to use to serialize LastActivity
        /// </summary>
        public static string LastActivityFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Updated
        /// </summary>
        public static string UpdatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="AdditionalCampaignProperties" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AdditionalCampaignProperties Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<AdditionalCampaignProperties.FrontendStateEnum?> frontendState = default;
            Option<bool?> storesImported = default;
            Option<List<CampaignBudget>> budgets = default;
            Option<long?> couponRedemptionCount = default;
            Option<long?> referralRedemptionCount = default;
            Option<decimal?> discountCount = default;
            Option<long?> discountEffectCount = default;
            Option<long?> couponCreationCount = default;
            Option<long?> customEffectCount = default;
            Option<long?> referralCreationCount = default;
            Option<long?> addFreeItemEffectCount = default;
            Option<long?> awardedGiveawaysCount = default;
            Option<decimal?> createdLoyaltyPointsCount = default;
            Option<long?> createdLoyaltyPointsEffectCount = default;
            Option<decimal?> redeemedLoyaltyPointsCount = default;
            Option<long?> redeemedLoyaltyPointsEffectCount = default;
            Option<long?> callApiEffectCount = default;
            Option<long?> reservecouponEffectCount = default;
            Option<DateTime?> lastActivity = default;
            Option<DateTime?> updated = default;
            Option<string> createdBy = default;
            Option<string> updatedBy = default;
            Option<long?> templateId = default;
            Option<List<long>> valueMapsIds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "frontendState":
                            string frontendStateRawValue = utf8JsonReader.GetString();
                            if (frontendStateRawValue != null)
                                frontendState = new Option<AdditionalCampaignProperties.FrontendStateEnum?>(AdditionalCampaignProperties.FrontendStateEnumFromStringOrDefault(frontendStateRawValue));
                            break;
                        case "storesImported":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                storesImported = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "budgets":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                budgets = new Option<List<CampaignBudget>>(JsonSerializer.Deserialize<List<CampaignBudget>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "couponRedemptionCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                couponRedemptionCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "referralRedemptionCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                referralRedemptionCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "discountCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                discountCount = new Option<decimal?>(utf8JsonReader.GetDecimal());
                            break;
                        case "discountEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                discountEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "couponCreationCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                couponCreationCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "customEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                customEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "referralCreationCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                referralCreationCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "addFreeItemEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                addFreeItemEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "awardedGiveawaysCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                awardedGiveawaysCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "createdLoyaltyPointsCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdLoyaltyPointsCount = new Option<decimal?>(utf8JsonReader.GetDecimal());
                            break;
                        case "createdLoyaltyPointsEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdLoyaltyPointsEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "redeemedLoyaltyPointsCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                redeemedLoyaltyPointsCount = new Option<decimal?>(utf8JsonReader.GetDecimal());
                            break;
                        case "redeemedLoyaltyPointsEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                redeemedLoyaltyPointsEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "callApiEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                callApiEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "reservecouponEffectCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                reservecouponEffectCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "lastActivity":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                lastActivity = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                updated = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "createdBy":
                            createdBy = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "updatedBy":
                            updatedBy = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "templateId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                templateId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "valueMapsIds":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                valueMapsIds = new Option<List<long>>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!frontendState.IsSet)
                throw new ArgumentException("Property is required for class AdditionalCampaignProperties.", nameof(frontendState));

            if (!storesImported.IsSet)
                throw new ArgumentException("Property is required for class AdditionalCampaignProperties.", nameof(storesImported));

            if (frontendState.IsSet && frontendState.Value == null)
                throw new ArgumentNullException(nameof(frontendState), "Property is not nullable for class AdditionalCampaignProperties.");

            if (storesImported.IsSet && storesImported.Value == null)
                throw new ArgumentNullException(nameof(storesImported), "Property is not nullable for class AdditionalCampaignProperties.");

            if (budgets.IsSet && budgets.Value == null)
                throw new ArgumentNullException(nameof(budgets), "Property is not nullable for class AdditionalCampaignProperties.");

            if (couponRedemptionCount.IsSet && couponRedemptionCount.Value == null)
                throw new ArgumentNullException(nameof(couponRedemptionCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (referralRedemptionCount.IsSet && referralRedemptionCount.Value == null)
                throw new ArgumentNullException(nameof(referralRedemptionCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (discountCount.IsSet && discountCount.Value == null)
                throw new ArgumentNullException(nameof(discountCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (discountEffectCount.IsSet && discountEffectCount.Value == null)
                throw new ArgumentNullException(nameof(discountEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (couponCreationCount.IsSet && couponCreationCount.Value == null)
                throw new ArgumentNullException(nameof(couponCreationCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (customEffectCount.IsSet && customEffectCount.Value == null)
                throw new ArgumentNullException(nameof(customEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (referralCreationCount.IsSet && referralCreationCount.Value == null)
                throw new ArgumentNullException(nameof(referralCreationCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (addFreeItemEffectCount.IsSet && addFreeItemEffectCount.Value == null)
                throw new ArgumentNullException(nameof(addFreeItemEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (awardedGiveawaysCount.IsSet && awardedGiveawaysCount.Value == null)
                throw new ArgumentNullException(nameof(awardedGiveawaysCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (createdLoyaltyPointsCount.IsSet && createdLoyaltyPointsCount.Value == null)
                throw new ArgumentNullException(nameof(createdLoyaltyPointsCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (createdLoyaltyPointsEffectCount.IsSet && createdLoyaltyPointsEffectCount.Value == null)
                throw new ArgumentNullException(nameof(createdLoyaltyPointsEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (redeemedLoyaltyPointsCount.IsSet && redeemedLoyaltyPointsCount.Value == null)
                throw new ArgumentNullException(nameof(redeemedLoyaltyPointsCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (redeemedLoyaltyPointsEffectCount.IsSet && redeemedLoyaltyPointsEffectCount.Value == null)
                throw new ArgumentNullException(nameof(redeemedLoyaltyPointsEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (callApiEffectCount.IsSet && callApiEffectCount.Value == null)
                throw new ArgumentNullException(nameof(callApiEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (reservecouponEffectCount.IsSet && reservecouponEffectCount.Value == null)
                throw new ArgumentNullException(nameof(reservecouponEffectCount), "Property is not nullable for class AdditionalCampaignProperties.");

            if (lastActivity.IsSet && lastActivity.Value == null)
                throw new ArgumentNullException(nameof(lastActivity), "Property is not nullable for class AdditionalCampaignProperties.");

            if (updated.IsSet && updated.Value == null)
                throw new ArgumentNullException(nameof(updated), "Property is not nullable for class AdditionalCampaignProperties.");

            if (createdBy.IsSet && createdBy.Value == null)
                throw new ArgumentNullException(nameof(createdBy), "Property is not nullable for class AdditionalCampaignProperties.");

            if (updatedBy.IsSet && updatedBy.Value == null)
                throw new ArgumentNullException(nameof(updatedBy), "Property is not nullable for class AdditionalCampaignProperties.");

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class AdditionalCampaignProperties.");

            if (valueMapsIds.IsSet && valueMapsIds.Value == null)
                throw new ArgumentNullException(nameof(valueMapsIds), "Property is not nullable for class AdditionalCampaignProperties.");

            return new AdditionalCampaignProperties(frontendState.Value.Value, storesImported.Value.Value, budgets, couponRedemptionCount, referralRedemptionCount, discountCount, discountEffectCount, couponCreationCount, customEffectCount, referralCreationCount, addFreeItemEffectCount, awardedGiveawaysCount, createdLoyaltyPointsCount, createdLoyaltyPointsEffectCount, redeemedLoyaltyPointsCount, redeemedLoyaltyPointsEffectCount, callApiEffectCount, reservecouponEffectCount, lastActivity, updated, createdBy, updatedBy, templateId, valueMapsIds);
        }

        /// <summary>
        /// Serializes a <see cref="AdditionalCampaignProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="additionalCampaignProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AdditionalCampaignProperties additionalCampaignProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, additionalCampaignProperties, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AdditionalCampaignProperties" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="additionalCampaignProperties"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AdditionalCampaignProperties additionalCampaignProperties, JsonSerializerOptions jsonSerializerOptions)
        {
            if (additionalCampaignProperties.BudgetsOption.IsSet && additionalCampaignProperties.Budgets == null)
                throw new ArgumentNullException(nameof(additionalCampaignProperties.Budgets), "Property is required for class AdditionalCampaignProperties.");

            if (additionalCampaignProperties.CreatedByOption.IsSet && additionalCampaignProperties.CreatedBy == null)
                throw new ArgumentNullException(nameof(additionalCampaignProperties.CreatedBy), "Property is required for class AdditionalCampaignProperties.");

            if (additionalCampaignProperties.UpdatedByOption.IsSet && additionalCampaignProperties.UpdatedBy == null)
                throw new ArgumentNullException(nameof(additionalCampaignProperties.UpdatedBy), "Property is required for class AdditionalCampaignProperties.");

            if (additionalCampaignProperties.ValueMapsIdsOption.IsSet && additionalCampaignProperties.ValueMapsIds == null)
                throw new ArgumentNullException(nameof(additionalCampaignProperties.ValueMapsIds), "Property is required for class AdditionalCampaignProperties.");

            var frontendStateRawValue = AdditionalCampaignProperties.FrontendStateEnumToJsonValue(additionalCampaignProperties.FrontendState);
            writer.WriteString("frontendState", frontendStateRawValue);
            writer.WriteBoolean("storesImported", additionalCampaignProperties.StoresImported);

            if (additionalCampaignProperties.BudgetsOption.IsSet)
            {
                writer.WritePropertyName("budgets");
                JsonSerializer.Serialize(writer, additionalCampaignProperties.Budgets, jsonSerializerOptions);
            }
            if (additionalCampaignProperties.CouponRedemptionCountOption.IsSet)
                writer.WriteNumber("couponRedemptionCount", additionalCampaignProperties.CouponRedemptionCountOption.Value.Value);

            if (additionalCampaignProperties.ReferralRedemptionCountOption.IsSet)
                writer.WriteNumber("referralRedemptionCount", additionalCampaignProperties.ReferralRedemptionCountOption.Value.Value);

            if (additionalCampaignProperties.DiscountCountOption.IsSet)
                writer.WriteNumber("discountCount", additionalCampaignProperties.DiscountCountOption.Value.Value);

            if (additionalCampaignProperties.DiscountEffectCountOption.IsSet)
                writer.WriteNumber("discountEffectCount", additionalCampaignProperties.DiscountEffectCountOption.Value.Value);

            if (additionalCampaignProperties.CouponCreationCountOption.IsSet)
                writer.WriteNumber("couponCreationCount", additionalCampaignProperties.CouponCreationCountOption.Value.Value);

            if (additionalCampaignProperties.CustomEffectCountOption.IsSet)
                writer.WriteNumber("customEffectCount", additionalCampaignProperties.CustomEffectCountOption.Value.Value);

            if (additionalCampaignProperties.ReferralCreationCountOption.IsSet)
                writer.WriteNumber("referralCreationCount", additionalCampaignProperties.ReferralCreationCountOption.Value.Value);

            if (additionalCampaignProperties.AddFreeItemEffectCountOption.IsSet)
                writer.WriteNumber("addFreeItemEffectCount", additionalCampaignProperties.AddFreeItemEffectCountOption.Value.Value);

            if (additionalCampaignProperties.AwardedGiveawaysCountOption.IsSet)
                writer.WriteNumber("awardedGiveawaysCount", additionalCampaignProperties.AwardedGiveawaysCountOption.Value.Value);

            if (additionalCampaignProperties.CreatedLoyaltyPointsCountOption.IsSet)
                writer.WriteNumber("createdLoyaltyPointsCount", additionalCampaignProperties.CreatedLoyaltyPointsCountOption.Value.Value);

            if (additionalCampaignProperties.CreatedLoyaltyPointsEffectCountOption.IsSet)
                writer.WriteNumber("createdLoyaltyPointsEffectCount", additionalCampaignProperties.CreatedLoyaltyPointsEffectCountOption.Value.Value);

            if (additionalCampaignProperties.RedeemedLoyaltyPointsCountOption.IsSet)
                writer.WriteNumber("redeemedLoyaltyPointsCount", additionalCampaignProperties.RedeemedLoyaltyPointsCountOption.Value.Value);

            if (additionalCampaignProperties.RedeemedLoyaltyPointsEffectCountOption.IsSet)
                writer.WriteNumber("redeemedLoyaltyPointsEffectCount", additionalCampaignProperties.RedeemedLoyaltyPointsEffectCountOption.Value.Value);

            if (additionalCampaignProperties.CallApiEffectCountOption.IsSet)
                writer.WriteNumber("callApiEffectCount", additionalCampaignProperties.CallApiEffectCountOption.Value.Value);

            if (additionalCampaignProperties.ReservecouponEffectCountOption.IsSet)
                writer.WriteNumber("reservecouponEffectCount", additionalCampaignProperties.ReservecouponEffectCountOption.Value.Value);

            if (additionalCampaignProperties.LastActivityOption.IsSet)
                writer.WriteString("lastActivity", additionalCampaignProperties.LastActivityOption.Value.Value.ToString(LastActivityFormat));

            if (additionalCampaignProperties.UpdatedOption.IsSet)
                writer.WriteString("updated", additionalCampaignProperties.UpdatedOption.Value.Value.ToString(UpdatedFormat));

            if (additionalCampaignProperties.CreatedByOption.IsSet)
                writer.WriteString("createdBy", additionalCampaignProperties.CreatedBy);

            if (additionalCampaignProperties.UpdatedByOption.IsSet)
                writer.WriteString("updatedBy", additionalCampaignProperties.UpdatedBy);

            if (additionalCampaignProperties.TemplateIdOption.IsSet)
                writer.WriteNumber("templateId", additionalCampaignProperties.TemplateIdOption.Value.Value);

            if (additionalCampaignProperties.ValueMapsIdsOption.IsSet)
            {
                writer.WritePropertyName("valueMapsIds");
                JsonSerializer.Serialize(writer, additionalCampaignProperties.ValueMapsIds, jsonSerializerOptions);
            }
        }
    }
}
