// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOne.Client;

namespace TalonOne.Model
{
    /// <summary>
    /// BaseNotificationWebhook
    /// </summary>
    public partial class BaseNotificationWebhook : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BaseNotificationWebhook" /> class.
        /// </summary>
        /// <param name="id">The internal ID of this entity.</param>
        /// <param name="created">The time this entity was created.</param>
        /// <param name="modified">The time this entity was last modified.</param>
        /// <param name="url">API URL for the given webhook-based notification.</param>
        /// <param name="headers">List of API HTTP headers for the given webhook-based notification.</param>
        /// <param name="enabled">Indicates whether the notification is activated. (default to true)</param>
        [JsonConstructor]
        public BaseNotificationWebhook(long id, DateTime created, DateTime modified, string url, List<string> headers, Option<bool?> enabled = default)
        {
            Id = id;
            Created = created;
            Modified = modified;
            Url = url;
            Headers = headers;
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The internal ID of this entity.
        /// </summary>
        /// <value>The internal ID of this entity.</value>
        /* <example>6</example> */
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// The time this entity was created.
        /// </summary>
        /// <value>The time this entity was created.</value>
        /* <example>2020-06-10T09:05:27.993483Z</example> */
        [JsonPropertyName("created")]
        public DateTime Created { get; set; }

        /// <summary>
        /// The time this entity was last modified.
        /// </summary>
        /// <value>The time this entity was last modified.</value>
        /* <example>2021-09-12T10:12:42Z</example> */
        [JsonPropertyName("modified")]
        public DateTime Modified { get; set; }

        /// <summary>
        /// API URL for the given webhook-based notification.
        /// </summary>
        /// <value>API URL for the given webhook-based notification.</value>
        /* <example>www.my-company.com/my-endpoint-name</example> */
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// List of API HTTP headers for the given webhook-based notification.
        /// </summary>
        /// <value>List of API HTTP headers for the given webhook-based notification.</value>
        [JsonPropertyName("headers")]
        public List<string> Headers { get; set; }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Indicates whether the notification is activated.
        /// </summary>
        /// <value>Indicates whether the notification is activated.</value>
        /* <example>true</example> */
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption; } set { this.EnabledOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BaseNotificationWebhook {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BaseNotificationWebhook" />
    /// </summary>
    public class BaseNotificationWebhookJsonConverter : JsonConverter<BaseNotificationWebhook>
    {
        /// <summary>
        /// The format to use to serialize Created
        /// </summary>
        public static string CreatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Modified
        /// </summary>
        public static string ModifiedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="BaseNotificationWebhook" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BaseNotificationWebhook Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<DateTime?> created = default;
            Option<DateTime?> modified = default;
            Option<string> url = default;
            Option<List<string>> headers = default;
            Option<bool?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "created":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                created = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "modified":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                modified = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "url":
                            url = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "headers":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                headers = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "enabled":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enabled = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class BaseNotificationWebhook.", nameof(id));

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class BaseNotificationWebhook.", nameof(created));

            if (!modified.IsSet)
                throw new ArgumentException("Property is required for class BaseNotificationWebhook.", nameof(modified));

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class BaseNotificationWebhook.", nameof(url));

            if (!headers.IsSet)
                throw new ArgumentException("Property is required for class BaseNotificationWebhook.", nameof(headers));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class BaseNotificationWebhook.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class BaseNotificationWebhook.");

            if (modified.IsSet && modified.Value == null)
                throw new ArgumentNullException(nameof(modified), "Property is not nullable for class BaseNotificationWebhook.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class BaseNotificationWebhook.");

            if (headers.IsSet && headers.Value == null)
                throw new ArgumentNullException(nameof(headers), "Property is not nullable for class BaseNotificationWebhook.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class BaseNotificationWebhook.");

            return new BaseNotificationWebhook(id.Value.Value, created.Value.Value, modified.Value.Value, url.Value, headers.Value, enabled);
        }

        /// <summary>
        /// Serializes a <see cref="BaseNotificationWebhook" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="baseNotificationWebhook"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BaseNotificationWebhook baseNotificationWebhook, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, baseNotificationWebhook, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BaseNotificationWebhook" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="baseNotificationWebhook"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BaseNotificationWebhook baseNotificationWebhook, JsonSerializerOptions jsonSerializerOptions)
        {
            if (baseNotificationWebhook.Url == null)
                throw new ArgumentNullException(nameof(baseNotificationWebhook.Url), "Property is required for class BaseNotificationWebhook.");

            if (baseNotificationWebhook.Headers == null)
                throw new ArgumentNullException(nameof(baseNotificationWebhook.Headers), "Property is required for class BaseNotificationWebhook.");

            writer.WriteNumber("id", baseNotificationWebhook.Id);

            writer.WriteString("created", baseNotificationWebhook.Created.ToString(CreatedFormat));

            writer.WriteString("modified", baseNotificationWebhook.Modified.ToString(ModifiedFormat));

            writer.WriteString("url", baseNotificationWebhook.Url);

            writer.WritePropertyName("headers");
            JsonSerializer.Serialize(writer, baseNotificationWebhook.Headers, jsonSerializerOptions);
            if (baseNotificationWebhook.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", baseNotificationWebhook.EnabledOption.Value.Value);
        }
    }
}
