// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOne.Client;

namespace TalonOne.Model
{
    /// <summary>
    /// BulkOperationOnCampaigns
    /// </summary>
    public partial class BulkOperationOnCampaigns : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkOperationOnCampaigns" /> class.
        /// </summary>
        /// <param name="operation">The operation to perform on the specified campaign IDs. </param>
        /// <param name="campaignIds">The list of campaign IDs on which the operation will be performed.</param>
        /// <param name="activateAt">Timestamp when the revisions are finalized after the &#x60;activate_revision&#x60; operation. The current time is used when left blank.  **Note:** It must be an RFC3339 timestamp string. </param>
        [JsonConstructor]
        public BulkOperationOnCampaigns(OperationEnum operation, List<long> campaignIds, Option<DateTime?> activateAt = default)
        {
            Operation = operation;
            CampaignIds = campaignIds;
            ActivateAtOption = activateAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The operation to perform on the specified campaign IDs. 
        /// </summary>
        /// <value>The operation to perform on the specified campaign IDs. </value>
        public enum OperationEnum
        {
            /// <summary>
            /// Enum Disable for value: disable
            /// </summary>
            Disable = 1,

            /// <summary>
            /// Enum Delete for value: delete
            /// </summary>
            Delete = 2,

            /// <summary>
            /// Enum ActivateRevision for value: activate_revision
            /// </summary>
            ActivateRevision = 3
        }

        /// <summary>
        /// Returns a <see cref="OperationEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OperationEnum OperationEnumFromString(string value)
        {
            if (value.Equals("disable"))
                return OperationEnum.Disable;

            if (value.Equals("delete"))
                return OperationEnum.Delete;

            if (value.Equals("activate_revision"))
                return OperationEnum.ActivateRevision;

            throw new NotImplementedException($"Could not convert value to type OperationEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OperationEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OperationEnum? OperationEnumFromStringOrDefault(string value)
        {
            if (value.Equals("disable"))
                return OperationEnum.Disable;

            if (value.Equals("delete"))
                return OperationEnum.Delete;

            if (value.Equals("activate_revision"))
                return OperationEnum.ActivateRevision;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OperationEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OperationEnumToJsonValue(OperationEnum value)
        {
            if (value == OperationEnum.Disable)
                return "disable";

            if (value == OperationEnum.Delete)
                return "delete";

            if (value == OperationEnum.ActivateRevision)
                return "activate_revision";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The operation to perform on the specified campaign IDs. 
        /// </summary>
        /// <value>The operation to perform on the specified campaign IDs. </value>
        [JsonPropertyName("operation")]
        public OperationEnum Operation { get; set; }

        /// <summary>
        /// The list of campaign IDs on which the operation will be performed.
        /// </summary>
        /// <value>The list of campaign IDs on which the operation will be performed.</value>
        /* <example>[1,2,3]</example> */
        [JsonPropertyName("campaignIds")]
        public List<long> CampaignIds { get; set; }

        /// <summary>
        /// Used to track the state of ActivateAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ActivateAtOption { get; private set; }

        /// <summary>
        /// Timestamp when the revisions are finalized after the &#x60;activate_revision&#x60; operation. The current time is used when left blank.  **Note:** It must be an RFC3339 timestamp string. 
        /// </summary>
        /// <value>Timestamp when the revisions are finalized after the &#x60;activate_revision&#x60; operation. The current time is used when left blank.  **Note:** It must be an RFC3339 timestamp string. </value>
        /* <example>2024-10-01T16:00:05Z07:00</example> */
        [JsonPropertyName("activateAt")]
        public DateTime? ActivateAt { get { return this.ActivateAtOption; } set { this.ActivateAtOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkOperationOnCampaigns {\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  CampaignIds: ").Append(CampaignIds).Append("\n");
            sb.Append("  ActivateAt: ").Append(ActivateAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkOperationOnCampaigns" />
    /// </summary>
    public class BulkOperationOnCampaignsJsonConverter : JsonConverter<BulkOperationOnCampaigns>
    {
        /// <summary>
        /// The format to use to serialize ActivateAt
        /// </summary>
        public static string ActivateAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="BulkOperationOnCampaigns" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkOperationOnCampaigns Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<BulkOperationOnCampaigns.OperationEnum?> operation = default;
            Option<List<long>> campaignIds = default;
            Option<DateTime?> activateAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "operation":
                            string operationRawValue = utf8JsonReader.GetString();
                            if (operationRawValue != null)
                                operation = new Option<BulkOperationOnCampaigns.OperationEnum?>(BulkOperationOnCampaigns.OperationEnumFromStringOrDefault(operationRawValue));
                            break;
                        case "campaignIds":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                campaignIds = new Option<List<long>>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "activateAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                activateAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!operation.IsSet)
                throw new ArgumentException("Property is required for class BulkOperationOnCampaigns.", nameof(operation));

            if (!campaignIds.IsSet)
                throw new ArgumentException("Property is required for class BulkOperationOnCampaigns.", nameof(campaignIds));

            if (operation.IsSet && operation.Value == null)
                throw new ArgumentNullException(nameof(operation), "Property is not nullable for class BulkOperationOnCampaigns.");

            if (campaignIds.IsSet && campaignIds.Value == null)
                throw new ArgumentNullException(nameof(campaignIds), "Property is not nullable for class BulkOperationOnCampaigns.");

            if (activateAt.IsSet && activateAt.Value == null)
                throw new ArgumentNullException(nameof(activateAt), "Property is not nullable for class BulkOperationOnCampaigns.");

            return new BulkOperationOnCampaigns(operation.Value.Value, campaignIds.Value, activateAt);
        }

        /// <summary>
        /// Serializes a <see cref="BulkOperationOnCampaigns" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkOperationOnCampaigns"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkOperationOnCampaigns bulkOperationOnCampaigns, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkOperationOnCampaigns, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkOperationOnCampaigns" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkOperationOnCampaigns"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkOperationOnCampaigns bulkOperationOnCampaigns, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bulkOperationOnCampaigns.CampaignIds == null)
                throw new ArgumentNullException(nameof(bulkOperationOnCampaigns.CampaignIds), "Property is required for class BulkOperationOnCampaigns.");

            var operationRawValue = BulkOperationOnCampaigns.OperationEnumToJsonValue(bulkOperationOnCampaigns.Operation);
            writer.WriteString("operation", operationRawValue);
            writer.WritePropertyName("campaignIds");
            JsonSerializer.Serialize(writer, bulkOperationOnCampaigns.CampaignIds, jsonSerializerOptions);
            if (bulkOperationOnCampaigns.ActivateAtOption.IsSet)
                writer.WriteString("activateAt", bulkOperationOnCampaigns.ActivateAtOption.Value.Value.ToString(ActivateAtFormat));
        }
    }
}
