// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOne.Client;

namespace TalonOne.Model
{
    /// <summary>
    /// CampaignTemplate
    /// </summary>
    public partial class CampaignTemplate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CampaignTemplate" /> class.
        /// </summary>
        /// <param name="id">The internal ID of this entity.</param>
        /// <param name="created">The time this entity was created.</param>
        /// <param name="accountId">The ID of the account that owns this entity.</param>
        /// <param name="userId">The ID of the user associated with this entity.</param>
        /// <param name="name">The campaign template name.</param>
        /// <param name="description">Customer-facing text that explains the objective of the template.</param>
        /// <param name="instructions">Customer-facing text that explains how to use the template. For example, you can use this property to explain the available attributes of this template, and how they can be modified when a user uses this template to create a new campaign.</param>
        /// <param name="state">Only campaign templates in &#39;available&#39; state may be used to create campaigns.</param>
        /// <param name="applicationsIds">applicationsIds</param>
        /// <param name="validApplicationIds">The IDs of the Applications that are related to this entity.</param>
        /// <param name="campaignAttributes">The campaign attributes that campaigns created from this template will have by default.</param>
        /// <param name="couponAttributes">The campaign attributes that coupons created from this template will have by default.</param>
        /// <param name="activeRulesetId">The ID of the ruleset this campaign template will use.</param>
        /// <param name="tags">A list of tags for the campaign template.</param>
        /// <param name="features">A list of features for the campaign template.</param>
        /// <param name="couponSettings">couponSettings</param>
        /// <param name="couponReservationSettings">couponReservationSettings</param>
        /// <param name="referralSettings">referralSettings</param>
        /// <param name="limits">The set of limits that operate for this campaign template.</param>
        /// <param name="templateParams">Fields which can be used to replace values in a rule.</param>
        /// <param name="campaignCollections">The campaign collections from the blueprint campaign for the template.</param>
        /// <param name="defaultCampaignGroupId">The default campaign group ID.</param>
        /// <param name="campaignType">The campaign type. Possible type values:   - &#x60;cartItem&#x60;: Type of campaign that can apply effects only to cart items.   - &#x60;advanced&#x60;: Type of campaign that can apply effects to customer sessions and cart items.  (default to CampaignTypeEnum.Advanced)</param>
        /// <param name="campaignsCount">The number of Campaigns created from this template.</param>
        /// <param name="updated">Timestamp of the most recent update to the campaign template or any of its elements.</param>
        /// <param name="updatedBy">Name of the user who last updated this campaign template, if available.</param>
        /// <param name="isUserFavorite">A flag indicating whether the user marked the template as a favorite. (default to false)</param>
        [JsonConstructor]
        public CampaignTemplate(long id, DateTime created, long accountId, long userId, string name, string description, string instructions, StateEnum state, List<long> applicationsIds, List<long> validApplicationIds, Option<Object> campaignAttributes = default, Option<Object> couponAttributes = default, Option<long?> activeRulesetId = default, Option<List<string>> tags = default, Option<List<CampaignTemplate.FeaturesEnum>> features = default, Option<CodeGeneratorSettings> couponSettings = default, Option<CampaignTemplateCouponReservationSettings> couponReservationSettings = default, Option<CodeGeneratorSettings> referralSettings = default, Option<List<TemplateLimitConfig>> limits = default, Option<List<CampaignTemplateParams>> templateParams = default, Option<List<CampaignTemplateCollection>> campaignCollections = default, Option<long?> defaultCampaignGroupId = default, Option<CampaignTypeEnum?> campaignType = default, Option<long?> campaignsCount = default, Option<DateTime?> updated = default, Option<string> updatedBy = default, Option<bool?> isUserFavorite = default)
        {
            Id = id;
            Created = created;
            AccountId = accountId;
            UserId = userId;
            Name = name;
            Description = description;
            Instructions = instructions;
            State = state;
            ApplicationsIds = applicationsIds;
            ValidApplicationIds = validApplicationIds;
            CampaignAttributesOption = campaignAttributes;
            CouponAttributesOption = couponAttributes;
            ActiveRulesetIdOption = activeRulesetId;
            TagsOption = tags;
            FeaturesOption = features;
            CouponSettingsOption = couponSettings;
            CouponReservationSettingsOption = couponReservationSettings;
            ReferralSettingsOption = referralSettings;
            LimitsOption = limits;
            TemplateParamsOption = templateParams;
            CampaignCollectionsOption = campaignCollections;
            DefaultCampaignGroupIdOption = defaultCampaignGroupId;
            CampaignTypeOption = campaignType;
            CampaignsCountOption = campaignsCount;
            UpdatedOption = updated;
            UpdatedByOption = updatedBy;
            IsUserFavoriteOption = isUserFavorite;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Only campaign templates in &#39;available&#39; state may be used to create campaigns.
        /// </summary>
        /// <value>Only campaign templates in &#39;available&#39; state may be used to create campaigns.</value>
        public enum StateEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            Draft = 1,

            /// <summary>
            /// Enum Enabled for value: enabled
            /// </summary>
            Enabled = 2,

            /// <summary>
            /// Enum Disabled for value: disabled
            /// </summary>
            Disabled = 3
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StateEnum StateEnumFromString(string value)
        {
            if (value.Equals("draft"))
                return StateEnum.Draft;

            if (value.Equals("enabled"))
                return StateEnum.Enabled;

            if (value.Equals("disabled"))
                return StateEnum.Disabled;

            throw new NotImplementedException($"Could not convert value to type StateEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StateEnum? StateEnumFromStringOrDefault(string value)
        {
            if (value.Equals("draft"))
                return StateEnum.Draft;

            if (value.Equals("enabled"))
                return StateEnum.Enabled;

            if (value.Equals("disabled"))
                return StateEnum.Disabled;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StateEnumToJsonValue(StateEnum value)
        {
            if (value == StateEnum.Draft)
                return "draft";

            if (value == StateEnum.Enabled)
                return "enabled";

            if (value == StateEnum.Disabled)
                return "disabled";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Only campaign templates in &#39;available&#39; state may be used to create campaigns.
        /// </summary>
        /// <value>Only campaign templates in &#39;available&#39; state may be used to create campaigns.</value>
        [JsonPropertyName("state")]
        public StateEnum State { get; set; }

        /// <summary>
        /// Defines Features
        /// </summary>
        public enum FeaturesEnum
        {
            /// <summary>
            /// Enum Coupons for value: coupons
            /// </summary>
            Coupons = 1,

            /// <summary>
            /// Enum Referrals for value: referrals
            /// </summary>
            Referrals = 2,

            /// <summary>
            /// Enum Loyalty for value: loyalty
            /// </summary>
            Loyalty = 3,

            /// <summary>
            /// Enum Giveaways for value: giveaways
            /// </summary>
            Giveaways = 4,

            /// <summary>
            /// Enum Strikethrough for value: strikethrough
            /// </summary>
            Strikethrough = 5,

            /// <summary>
            /// Enum Achievements for value: achievements
            /// </summary>
            Achievements = 6
        }

        /// <summary>
        /// Returns a <see cref="FeaturesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FeaturesEnum FeaturesEnumFromString(string value)
        {
            if (value.Equals("coupons"))
                return FeaturesEnum.Coupons;

            if (value.Equals("referrals"))
                return FeaturesEnum.Referrals;

            if (value.Equals("loyalty"))
                return FeaturesEnum.Loyalty;

            if (value.Equals("giveaways"))
                return FeaturesEnum.Giveaways;

            if (value.Equals("strikethrough"))
                return FeaturesEnum.Strikethrough;

            if (value.Equals("achievements"))
                return FeaturesEnum.Achievements;

            throw new NotImplementedException($"Could not convert value to type FeaturesEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FeaturesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FeaturesEnum? FeaturesEnumFromStringOrDefault(string value)
        {
            if (value.Equals("coupons"))
                return FeaturesEnum.Coupons;

            if (value.Equals("referrals"))
                return FeaturesEnum.Referrals;

            if (value.Equals("loyalty"))
                return FeaturesEnum.Loyalty;

            if (value.Equals("giveaways"))
                return FeaturesEnum.Giveaways;

            if (value.Equals("strikethrough"))
                return FeaturesEnum.Strikethrough;

            if (value.Equals("achievements"))
                return FeaturesEnum.Achievements;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FeaturesEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FeaturesEnumToJsonValue(FeaturesEnum value)
        {
            if (value == FeaturesEnum.Coupons)
                return "coupons";

            if (value == FeaturesEnum.Referrals)
                return "referrals";

            if (value == FeaturesEnum.Loyalty)
                return "loyalty";

            if (value == FeaturesEnum.Giveaways)
                return "giveaways";

            if (value == FeaturesEnum.Strikethrough)
                return "strikethrough";

            if (value == FeaturesEnum.Achievements)
                return "achievements";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The campaign type. Possible type values:   - &#x60;cartItem&#x60;: Type of campaign that can apply effects only to cart items.   - &#x60;advanced&#x60;: Type of campaign that can apply effects to customer sessions and cart items. 
        /// </summary>
        /// <value>The campaign type. Possible type values:   - &#x60;cartItem&#x60;: Type of campaign that can apply effects only to cart items.   - &#x60;advanced&#x60;: Type of campaign that can apply effects to customer sessions and cart items. </value>
        public enum CampaignTypeEnum
        {
            /// <summary>
            /// Enum CartItem for value: cartItem
            /// </summary>
            CartItem = 1,

            /// <summary>
            /// Enum Advanced for value: advanced
            /// </summary>
            Advanced = 2
        }

        /// <summary>
        /// Returns a <see cref="CampaignTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CampaignTypeEnum CampaignTypeEnumFromString(string value)
        {
            if (value.Equals("cartItem"))
                return CampaignTypeEnum.CartItem;

            if (value.Equals("advanced"))
                return CampaignTypeEnum.Advanced;

            throw new NotImplementedException($"Could not convert value to type CampaignTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CampaignTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CampaignTypeEnum? CampaignTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("cartItem"))
                return CampaignTypeEnum.CartItem;

            if (value.Equals("advanced"))
                return CampaignTypeEnum.Advanced;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CampaignTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CampaignTypeEnumToJsonValue(CampaignTypeEnum? value)
        {
            if (value == CampaignTypeEnum.CartItem)
                return "cartItem";

            if (value == CampaignTypeEnum.Advanced)
                return "advanced";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of CampaignType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CampaignTypeEnum?> CampaignTypeOption { get; private set; }

        /// <summary>
        /// The campaign type. Possible type values:   - &#x60;cartItem&#x60;: Type of campaign that can apply effects only to cart items.   - &#x60;advanced&#x60;: Type of campaign that can apply effects to customer sessions and cart items. 
        /// </summary>
        /// <value>The campaign type. Possible type values:   - &#x60;cartItem&#x60;: Type of campaign that can apply effects only to cart items.   - &#x60;advanced&#x60;: Type of campaign that can apply effects to customer sessions and cart items. </value>
        /* <example>advanced</example> */
        [JsonPropertyName("campaignType")]
        public CampaignTypeEnum? CampaignType { get { return this.CampaignTypeOption; } set { this.CampaignTypeOption = new Option<CampaignTypeEnum?>(value); } }

        /// <summary>
        /// The internal ID of this entity.
        /// </summary>
        /// <value>The internal ID of this entity.</value>
        /* <example>6</example> */
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// The time this entity was created.
        /// </summary>
        /// <value>The time this entity was created.</value>
        /* <example>2020-06-10T09:05:27.993483Z</example> */
        [JsonPropertyName("created")]
        public DateTime Created { get; set; }

        /// <summary>
        /// The ID of the account that owns this entity.
        /// </summary>
        /// <value>The ID of the account that owns this entity.</value>
        /* <example>3886</example> */
        [JsonPropertyName("accountId")]
        public long AccountId { get; set; }

        /// <summary>
        /// The ID of the user associated with this entity.
        /// </summary>
        /// <value>The ID of the user associated with this entity.</value>
        /* <example>388</example> */
        [JsonPropertyName("userId")]
        public long UserId { get; set; }

        /// <summary>
        /// The campaign template name.
        /// </summary>
        /// <value>The campaign template name.</value>
        /* <example>Discount campaign</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Customer-facing text that explains the objective of the template.
        /// </summary>
        /// <value>Customer-facing text that explains the objective of the template.</value>
        /* <example>This is a template for a discount campaign.</example> */
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// Customer-facing text that explains how to use the template. For example, you can use this property to explain the available attributes of this template, and how they can be modified when a user uses this template to create a new campaign.
        /// </summary>
        /// <value>Customer-facing text that explains how to use the template. For example, you can use this property to explain the available attributes of this template, and how they can be modified when a user uses this template to create a new campaign.</value>
        /* <example>Use this template for discount campaigns. Set the campaign properties according to the campaign goals, and don&#39;t forget to set an end date.</example> */
        [JsonPropertyName("instructions")]
        public string Instructions { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationsIds
        /// </summary>
        /* <example>[1, 2, 3]</example> */
        [JsonPropertyName("applicationsIds")]
        public List<long> ApplicationsIds { get; set; }

        /// <summary>
        /// The IDs of the Applications that are related to this entity.
        /// </summary>
        /// <value>The IDs of the Applications that are related to this entity.</value>
        /* <example>[1, 2, 3]</example> */
        [JsonPropertyName("validApplicationIds")]
        public List<long> ValidApplicationIds { get; set; }

        /// <summary>
        /// Used to track the state of CampaignAttributes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object> CampaignAttributesOption { get; private set; }

        /// <summary>
        /// The campaign attributes that campaigns created from this template will have by default.
        /// </summary>
        /// <value>The campaign attributes that campaigns created from this template will have by default.</value>
        [JsonPropertyName("campaignAttributes")]
        public Object CampaignAttributes { get { return this.CampaignAttributesOption; } set { this.CampaignAttributesOption = new Option<Object>(value); } }

        /// <summary>
        /// Used to track the state of CouponAttributes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object> CouponAttributesOption { get; private set; }

        /// <summary>
        /// The campaign attributes that coupons created from this template will have by default.
        /// </summary>
        /// <value>The campaign attributes that coupons created from this template will have by default.</value>
        [JsonPropertyName("couponAttributes")]
        public Object CouponAttributes { get { return this.CouponAttributesOption; } set { this.CouponAttributesOption = new Option<Object>(value); } }

        /// <summary>
        /// Used to track the state of ActiveRulesetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ActiveRulesetIdOption { get; private set; }

        /// <summary>
        /// The ID of the ruleset this campaign template will use.
        /// </summary>
        /// <value>The ID of the ruleset this campaign template will use.</value>
        /* <example>5</example> */
        [JsonPropertyName("activeRulesetId")]
        public long? ActiveRulesetId { get { return this.ActiveRulesetIdOption; } set { this.ActiveRulesetIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> TagsOption { get; private set; }

        /// <summary>
        /// A list of tags for the campaign template.
        /// </summary>
        /// <value>A list of tags for the campaign template.</value>
        /* <example>[discount]</example> */
        [JsonPropertyName("tags")]
        public List<string> Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<List<string>>(value); } }

        /// <summary>
        /// Used to track the state of Features
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CampaignTemplate.FeaturesEnum>> FeaturesOption { get; private set; }

        /// <summary>
        /// A list of features for the campaign template.
        /// </summary>
        /// <value>A list of features for the campaign template.</value>
        [JsonPropertyName("features")]
        public List<CampaignTemplate.FeaturesEnum> Features { get { return this.FeaturesOption; } set { this.FeaturesOption = new Option<List<CampaignTemplate.FeaturesEnum>>(value); } }

        /// <summary>
        /// Used to track the state of CouponSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CodeGeneratorSettings> CouponSettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CouponSettings
        /// </summary>
        [JsonPropertyName("couponSettings")]
        public CodeGeneratorSettings CouponSettings { get { return this.CouponSettingsOption; } set { this.CouponSettingsOption = new Option<CodeGeneratorSettings>(value); } }

        /// <summary>
        /// Used to track the state of CouponReservationSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CampaignTemplateCouponReservationSettings> CouponReservationSettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CouponReservationSettings
        /// </summary>
        [JsonPropertyName("couponReservationSettings")]
        public CampaignTemplateCouponReservationSettings CouponReservationSettings { get { return this.CouponReservationSettingsOption; } set { this.CouponReservationSettingsOption = new Option<CampaignTemplateCouponReservationSettings>(value); } }

        /// <summary>
        /// Used to track the state of ReferralSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CodeGeneratorSettings> ReferralSettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReferralSettings
        /// </summary>
        [JsonPropertyName("referralSettings")]
        public CodeGeneratorSettings ReferralSettings { get { return this.ReferralSettingsOption; } set { this.ReferralSettingsOption = new Option<CodeGeneratorSettings>(value); } }

        /// <summary>
        /// Used to track the state of Limits
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TemplateLimitConfig>> LimitsOption { get; private set; }

        /// <summary>
        /// The set of limits that operate for this campaign template.
        /// </summary>
        /// <value>The set of limits that operate for this campaign template.</value>
        [JsonPropertyName("limits")]
        public List<TemplateLimitConfig> Limits { get { return this.LimitsOption; } set { this.LimitsOption = new Option<List<TemplateLimitConfig>>(value); } }

        /// <summary>
        /// Used to track the state of TemplateParams
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CampaignTemplateParams>> TemplateParamsOption { get; private set; }

        /// <summary>
        /// Fields which can be used to replace values in a rule.
        /// </summary>
        /// <value>Fields which can be used to replace values in a rule.</value>
        [JsonPropertyName("templateParams")]
        public List<CampaignTemplateParams> TemplateParams { get { return this.TemplateParamsOption; } set { this.TemplateParamsOption = new Option<List<CampaignTemplateParams>>(value); } }

        /// <summary>
        /// Used to track the state of CampaignCollections
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CampaignTemplateCollection>> CampaignCollectionsOption { get; private set; }

        /// <summary>
        /// The campaign collections from the blueprint campaign for the template.
        /// </summary>
        /// <value>The campaign collections from the blueprint campaign for the template.</value>
        [JsonPropertyName("campaignCollections")]
        public List<CampaignTemplateCollection> CampaignCollections { get { return this.CampaignCollectionsOption; } set { this.CampaignCollectionsOption = new Option<List<CampaignTemplateCollection>>(value); } }

        /// <summary>
        /// Used to track the state of DefaultCampaignGroupId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> DefaultCampaignGroupIdOption { get; private set; }

        /// <summary>
        /// The default campaign group ID.
        /// </summary>
        /// <value>The default campaign group ID.</value>
        /* <example>42</example> */
        [JsonPropertyName("defaultCampaignGroupId")]
        public long? DefaultCampaignGroupId { get { return this.DefaultCampaignGroupIdOption; } set { this.DefaultCampaignGroupIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of CampaignsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CampaignsCountOption { get; private set; }

        /// <summary>
        /// The number of Campaigns created from this template.
        /// </summary>
        /// <value>The number of Campaigns created from this template.</value>
        /* <example>3</example> */
        [JsonPropertyName("campaignsCount")]
        public long? CampaignsCount { get { return this.CampaignsCountOption; } set { this.CampaignsCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Updated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedOption { get; private set; }

        /// <summary>
        /// Timestamp of the most recent update to the campaign template or any of its elements.
        /// </summary>
        /// <value>Timestamp of the most recent update to the campaign template or any of its elements.</value>
        /* <example>2022-08-24T14:15:22Z</example> */
        [JsonPropertyName("updated")]
        public DateTime? Updated { get { return this.UpdatedOption; } set { this.UpdatedOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of UpdatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UpdatedByOption { get; private set; }

        /// <summary>
        /// Name of the user who last updated this campaign template, if available.
        /// </summary>
        /// <value>Name of the user who last updated this campaign template, if available.</value>
        /* <example>Jane Doe</example> */
        [JsonPropertyName("updatedBy")]
        public string UpdatedBy { get { return this.UpdatedByOption; } set { this.UpdatedByOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of IsUserFavorite
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsUserFavoriteOption { get; private set; }

        /// <summary>
        /// A flag indicating whether the user marked the template as a favorite.
        /// </summary>
        /// <value>A flag indicating whether the user marked the template as a favorite.</value>
        /* <example>false</example> */
        [JsonPropertyName("isUserFavorite")]
        public bool? IsUserFavorite { get { return this.IsUserFavoriteOption; } set { this.IsUserFavoriteOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CampaignTemplate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Instructions: ").Append(Instructions).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  ApplicationsIds: ").Append(ApplicationsIds).Append("\n");
            sb.Append("  ValidApplicationIds: ").Append(ValidApplicationIds).Append("\n");
            sb.Append("  CampaignAttributes: ").Append(CampaignAttributes).Append("\n");
            sb.Append("  CouponAttributes: ").Append(CouponAttributes).Append("\n");
            sb.Append("  ActiveRulesetId: ").Append(ActiveRulesetId).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Features: ").Append(Features).Append("\n");
            sb.Append("  CouponSettings: ").Append(CouponSettings).Append("\n");
            sb.Append("  CouponReservationSettings: ").Append(CouponReservationSettings).Append("\n");
            sb.Append("  ReferralSettings: ").Append(ReferralSettings).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  TemplateParams: ").Append(TemplateParams).Append("\n");
            sb.Append("  CampaignCollections: ").Append(CampaignCollections).Append("\n");
            sb.Append("  DefaultCampaignGroupId: ").Append(DefaultCampaignGroupId).Append("\n");
            sb.Append("  CampaignType: ").Append(CampaignType).Append("\n");
            sb.Append("  CampaignsCount: ").Append(CampaignsCount).Append("\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  IsUserFavorite: ").Append(IsUserFavorite).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CampaignTemplate" />
    /// </summary>
    public class CampaignTemplateJsonConverter : JsonConverter<CampaignTemplate>
    {
        /// <summary>
        /// The format to use to serialize Created
        /// </summary>
        public static string CreatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize Updated
        /// </summary>
        public static string UpdatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="CampaignTemplate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CampaignTemplate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<DateTime?> created = default;
            Option<long?> accountId = default;
            Option<long?> userId = default;
            Option<string> name = default;
            Option<string> description = default;
            Option<string> instructions = default;
            Option<CampaignTemplate.StateEnum?> state = default;
            Option<List<long>> applicationsIds = default;
            Option<List<long>> validApplicationIds = default;
            Option<Object> campaignAttributes = default;
            Option<Object> couponAttributes = default;
            Option<long?> activeRulesetId = default;
            Option<List<string>> tags = default;
            Option<List<CampaignTemplate.FeaturesEnum>> features = default;
            Option<CodeGeneratorSettings> couponSettings = default;
            Option<CampaignTemplateCouponReservationSettings> couponReservationSettings = default;
            Option<CodeGeneratorSettings> referralSettings = default;
            Option<List<TemplateLimitConfig>> limits = default;
            Option<List<CampaignTemplateParams>> templateParams = default;
            Option<List<CampaignTemplateCollection>> campaignCollections = default;
            Option<long?> defaultCampaignGroupId = default;
            Option<CampaignTemplate.CampaignTypeEnum?> campaignType = default;
            Option<long?> campaignsCount = default;
            Option<DateTime?> updated = default;
            Option<string> updatedBy = default;
            Option<bool?> isUserFavorite = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "created":
                            created = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "accountId":
                            accountId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "userId":
                            userId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "instructions":
                            instructions = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "state":
                            string stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                                state = new Option<CampaignTemplate.StateEnum?>(CampaignTemplate.StateEnumFromStringOrDefault(stateRawValue));
                            break;
                        case "applicationsIds":
                            applicationsIds = new Option<List<long>>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "validApplicationIds":
                            validApplicationIds = new Option<List<long>>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "campaignAttributes":
                            campaignAttributes = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "couponAttributes":
                            couponAttributes = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "activeRulesetId":
                            activeRulesetId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "tags":
                            tags = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "features":
                            features = new Option<List<CampaignTemplate.FeaturesEnum>>(JsonSerializer.Deserialize<List<CampaignTemplate.FeaturesEnum>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "couponSettings":
                            couponSettings = new Option<CodeGeneratorSettings>(JsonSerializer.Deserialize<CodeGeneratorSettings>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "couponReservationSettings":
                            couponReservationSettings = new Option<CampaignTemplateCouponReservationSettings>(JsonSerializer.Deserialize<CampaignTemplateCouponReservationSettings>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "referralSettings":
                            referralSettings = new Option<CodeGeneratorSettings>(JsonSerializer.Deserialize<CodeGeneratorSettings>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "limits":
                            limits = new Option<List<TemplateLimitConfig>>(JsonSerializer.Deserialize<List<TemplateLimitConfig>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "templateParams":
                            templateParams = new Option<List<CampaignTemplateParams>>(JsonSerializer.Deserialize<List<CampaignTemplateParams>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "campaignCollections":
                            campaignCollections = new Option<List<CampaignTemplateCollection>>(JsonSerializer.Deserialize<List<CampaignTemplateCollection>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "defaultCampaignGroupId":
                            defaultCampaignGroupId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "campaignType":
                            string campaignTypeRawValue = utf8JsonReader.GetString();
                            if (campaignTypeRawValue != null)
                                campaignType = new Option<CampaignTemplate.CampaignTypeEnum?>(CampaignTemplate.CampaignTypeEnumFromStringOrDefault(campaignTypeRawValue));
                            break;
                        case "campaignsCount":
                            campaignsCount = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "updated":
                            updated = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedBy":
                            updatedBy = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "isUserFavorite":
                            isUserFavorite = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(id));

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(created));

            if (!accountId.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(accountId));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(userId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(name));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(description));

            if (!instructions.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(instructions));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(state));

            if (!applicationsIds.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(applicationsIds));

            if (!validApplicationIds.IsSet)
                throw new ArgumentException("Property is required for class CampaignTemplate.", nameof(validApplicationIds));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class CampaignTemplate.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class CampaignTemplate.");

            if (accountId.IsSet && accountId.Value == null)
                throw new ArgumentNullException(nameof(accountId), "Property is not nullable for class CampaignTemplate.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class CampaignTemplate.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CampaignTemplate.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CampaignTemplate.");

            if (instructions.IsSet && instructions.Value == null)
                throw new ArgumentNullException(nameof(instructions), "Property is not nullable for class CampaignTemplate.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class CampaignTemplate.");

            if (applicationsIds.IsSet && applicationsIds.Value == null)
                throw new ArgumentNullException(nameof(applicationsIds), "Property is not nullable for class CampaignTemplate.");

            if (validApplicationIds.IsSet && validApplicationIds.Value == null)
                throw new ArgumentNullException(nameof(validApplicationIds), "Property is not nullable for class CampaignTemplate.");

            if (campaignAttributes.IsSet && campaignAttributes.Value == null)
                throw new ArgumentNullException(nameof(campaignAttributes), "Property is not nullable for class CampaignTemplate.");

            if (couponAttributes.IsSet && couponAttributes.Value == null)
                throw new ArgumentNullException(nameof(couponAttributes), "Property is not nullable for class CampaignTemplate.");

            if (activeRulesetId.IsSet && activeRulesetId.Value == null)
                throw new ArgumentNullException(nameof(activeRulesetId), "Property is not nullable for class CampaignTemplate.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class CampaignTemplate.");

            if (features.IsSet && features.Value == null)
                throw new ArgumentNullException(nameof(features), "Property is not nullable for class CampaignTemplate.");

            if (couponSettings.IsSet && couponSettings.Value == null)
                throw new ArgumentNullException(nameof(couponSettings), "Property is not nullable for class CampaignTemplate.");

            if (couponReservationSettings.IsSet && couponReservationSettings.Value == null)
                throw new ArgumentNullException(nameof(couponReservationSettings), "Property is not nullable for class CampaignTemplate.");

            if (referralSettings.IsSet && referralSettings.Value == null)
                throw new ArgumentNullException(nameof(referralSettings), "Property is not nullable for class CampaignTemplate.");

            if (limits.IsSet && limits.Value == null)
                throw new ArgumentNullException(nameof(limits), "Property is not nullable for class CampaignTemplate.");

            if (templateParams.IsSet && templateParams.Value == null)
                throw new ArgumentNullException(nameof(templateParams), "Property is not nullable for class CampaignTemplate.");

            if (campaignCollections.IsSet && campaignCollections.Value == null)
                throw new ArgumentNullException(nameof(campaignCollections), "Property is not nullable for class CampaignTemplate.");

            if (defaultCampaignGroupId.IsSet && defaultCampaignGroupId.Value == null)
                throw new ArgumentNullException(nameof(defaultCampaignGroupId), "Property is not nullable for class CampaignTemplate.");

            if (campaignType.IsSet && campaignType.Value == null)
                throw new ArgumentNullException(nameof(campaignType), "Property is not nullable for class CampaignTemplate.");

            if (campaignsCount.IsSet && campaignsCount.Value == null)
                throw new ArgumentNullException(nameof(campaignsCount), "Property is not nullable for class CampaignTemplate.");

            if (updated.IsSet && updated.Value == null)
                throw new ArgumentNullException(nameof(updated), "Property is not nullable for class CampaignTemplate.");

            if (updatedBy.IsSet && updatedBy.Value == null)
                throw new ArgumentNullException(nameof(updatedBy), "Property is not nullable for class CampaignTemplate.");

            if (isUserFavorite.IsSet && isUserFavorite.Value == null)
                throw new ArgumentNullException(nameof(isUserFavorite), "Property is not nullable for class CampaignTemplate.");

            return new CampaignTemplate(id.Value.Value, created.Value.Value, accountId.Value.Value, userId.Value.Value, name.Value, description.Value, instructions.Value, state.Value.Value, applicationsIds.Value, validApplicationIds.Value, campaignAttributes, couponAttributes, activeRulesetId, tags, features, couponSettings, couponReservationSettings, referralSettings, limits, templateParams, campaignCollections, defaultCampaignGroupId, campaignType, campaignsCount, updated, updatedBy, isUserFavorite);
        }

        /// <summary>
        /// Serializes a <see cref="CampaignTemplate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="campaignTemplate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CampaignTemplate campaignTemplate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, campaignTemplate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CampaignTemplate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="campaignTemplate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CampaignTemplate campaignTemplate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (campaignTemplate.Name == null)
                throw new ArgumentNullException(nameof(campaignTemplate.Name), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.Description == null)
                throw new ArgumentNullException(nameof(campaignTemplate.Description), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.Instructions == null)
                throw new ArgumentNullException(nameof(campaignTemplate.Instructions), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.ApplicationsIds == null)
                throw new ArgumentNullException(nameof(campaignTemplate.ApplicationsIds), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.ValidApplicationIds == null)
                throw new ArgumentNullException(nameof(campaignTemplate.ValidApplicationIds), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.CampaignAttributesOption.IsSet && campaignTemplate.CampaignAttributes == null)
                throw new ArgumentNullException(nameof(campaignTemplate.CampaignAttributes), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.CouponAttributesOption.IsSet && campaignTemplate.CouponAttributes == null)
                throw new ArgumentNullException(nameof(campaignTemplate.CouponAttributes), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.TagsOption.IsSet && campaignTemplate.Tags == null)
                throw new ArgumentNullException(nameof(campaignTemplate.Tags), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.FeaturesOption.IsSet && campaignTemplate.Features == null)
                throw new ArgumentNullException(nameof(campaignTemplate.Features), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.CouponSettingsOption.IsSet && campaignTemplate.CouponSettings == null)
                throw new ArgumentNullException(nameof(campaignTemplate.CouponSettings), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.CouponReservationSettingsOption.IsSet && campaignTemplate.CouponReservationSettings == null)
                throw new ArgumentNullException(nameof(campaignTemplate.CouponReservationSettings), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.ReferralSettingsOption.IsSet && campaignTemplate.ReferralSettings == null)
                throw new ArgumentNullException(nameof(campaignTemplate.ReferralSettings), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.LimitsOption.IsSet && campaignTemplate.Limits == null)
                throw new ArgumentNullException(nameof(campaignTemplate.Limits), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.TemplateParamsOption.IsSet && campaignTemplate.TemplateParams == null)
                throw new ArgumentNullException(nameof(campaignTemplate.TemplateParams), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.CampaignCollectionsOption.IsSet && campaignTemplate.CampaignCollections == null)
                throw new ArgumentNullException(nameof(campaignTemplate.CampaignCollections), "Property is required for class CampaignTemplate.");

            if (campaignTemplate.UpdatedByOption.IsSet && campaignTemplate.UpdatedBy == null)
                throw new ArgumentNullException(nameof(campaignTemplate.UpdatedBy), "Property is required for class CampaignTemplate.");

            writer.WriteNumber("id", campaignTemplate.Id);

            writer.WriteString("created", campaignTemplate.Created.ToString(CreatedFormat));

            writer.WriteNumber("accountId", campaignTemplate.AccountId);

            writer.WriteNumber("userId", campaignTemplate.UserId);

            writer.WriteString("name", campaignTemplate.Name);

            writer.WriteString("description", campaignTemplate.Description);

            writer.WriteString("instructions", campaignTemplate.Instructions);

            var stateRawValue = CampaignTemplate.StateEnumToJsonValue(campaignTemplate.State);
            writer.WriteString("state", stateRawValue);
            writer.WritePropertyName("applicationsIds");
            JsonSerializer.Serialize(writer, campaignTemplate.ApplicationsIds, jsonSerializerOptions);
            writer.WritePropertyName("validApplicationIds");
            JsonSerializer.Serialize(writer, campaignTemplate.ValidApplicationIds, jsonSerializerOptions);
            if (campaignTemplate.CampaignAttributesOption.IsSet)
            {
                writer.WritePropertyName("campaignAttributes");
                JsonSerializer.Serialize(writer, campaignTemplate.CampaignAttributes, jsonSerializerOptions);
            }
            if (campaignTemplate.CouponAttributesOption.IsSet)
            {
                writer.WritePropertyName("couponAttributes");
                JsonSerializer.Serialize(writer, campaignTemplate.CouponAttributes, jsonSerializerOptions);
            }
            if (campaignTemplate.ActiveRulesetIdOption.IsSet)
                writer.WriteNumber("activeRulesetId", campaignTemplate.ActiveRulesetIdOption.Value.Value);

            if (campaignTemplate.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, campaignTemplate.Tags, jsonSerializerOptions);
            }
            if (campaignTemplate.FeaturesOption.IsSet)
            {
                writer.WritePropertyName("features");
                JsonSerializer.Serialize(writer, campaignTemplate.Features, jsonSerializerOptions);
            }
            if (campaignTemplate.CouponSettingsOption.IsSet)
            {
                writer.WritePropertyName("couponSettings");
                JsonSerializer.Serialize(writer, campaignTemplate.CouponSettings, jsonSerializerOptions);
            }
            if (campaignTemplate.CouponReservationSettingsOption.IsSet)
            {
                writer.WritePropertyName("couponReservationSettings");
                JsonSerializer.Serialize(writer, campaignTemplate.CouponReservationSettings, jsonSerializerOptions);
            }
            if (campaignTemplate.ReferralSettingsOption.IsSet)
            {
                writer.WritePropertyName("referralSettings");
                JsonSerializer.Serialize(writer, campaignTemplate.ReferralSettings, jsonSerializerOptions);
            }
            if (campaignTemplate.LimitsOption.IsSet)
            {
                writer.WritePropertyName("limits");
                JsonSerializer.Serialize(writer, campaignTemplate.Limits, jsonSerializerOptions);
            }
            if (campaignTemplate.TemplateParamsOption.IsSet)
            {
                writer.WritePropertyName("templateParams");
                JsonSerializer.Serialize(writer, campaignTemplate.TemplateParams, jsonSerializerOptions);
            }
            if (campaignTemplate.CampaignCollectionsOption.IsSet)
            {
                writer.WritePropertyName("campaignCollections");
                JsonSerializer.Serialize(writer, campaignTemplate.CampaignCollections, jsonSerializerOptions);
            }
            if (campaignTemplate.DefaultCampaignGroupIdOption.IsSet)
                writer.WriteNumber("defaultCampaignGroupId", campaignTemplate.DefaultCampaignGroupIdOption.Value.Value);

            var campaignTypeRawValue = CampaignTemplate.CampaignTypeEnumToJsonValue(campaignTemplate.CampaignTypeOption.Value.Value);
            writer.WriteString("campaignType", campaignTypeRawValue);
            if (campaignTemplate.CampaignsCountOption.IsSet)
                writer.WriteNumber("campaignsCount", campaignTemplate.CampaignsCountOption.Value.Value);

            if (campaignTemplate.UpdatedOption.IsSet)
                writer.WriteString("updated", campaignTemplate.UpdatedOption.Value.Value.ToString(UpdatedFormat));

            if (campaignTemplate.UpdatedByOption.IsSet)
                writer.WriteString("updatedBy", campaignTemplate.UpdatedBy);

            if (campaignTemplate.IsUserFavoriteOption.IsSet)
                writer.WriteBoolean("isUserFavorite", campaignTemplate.IsUserFavoriteOption.Value.Value);
        }
    }
}
