// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOne.Client;

namespace TalonOne.Model
{
    /// <summary>
    /// NewCoupons
    /// </summary>
    public partial class NewCoupons : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewCoupons" /> class.
        /// </summary>
        /// <param name="numberOfCoupons">The number of new coupon codes to generate for the campaign. Must be at least 1.</param>
        /// <param name="usageLimit">The number of times the coupon code can be redeemed. &#x60;0&#x60; means unlimited redemptions but any campaign usage limits will still apply. </param>
        /// <param name="discountLimit">The total discount value that the code can give. Typically used to represent a gift card value. </param>
        /// <param name="reservationLimit">The number of reservations that can be made with this coupon code. </param>
        /// <param name="startDate">Timestamp at which point the coupon becomes valid.</param>
        /// <param name="expiryDate">Expiration date of the coupon. Coupon never expires if this is omitted.</param>
        /// <param name="limits">Limits configuration for a coupon. These limits will override the limits set from the campaign.  **Note:** Only usable when creating a single coupon which is not tied to a specific recipient. Only per-profile limits are allowed to be configured. </param>
        /// <param name="uniquePrefix">**DEPRECATED** To create more than 20,000 coupons in one request, use [Create coupons asynchronously](https://docs.talon.one/management-api#operation/createCouponsAsync) endpoint. </param>
        /// <param name="attributes">Arbitrary properties associated with this item.</param>
        /// <param name="recipientIntegrationId">The integration ID for this coupon&#39;s beneficiary&#39;s profile.</param>
        /// <param name="validCharacters">List of characters used to generate the random parts of a code. By default, the list of characters is equivalent to the &#x60;[A-Z, 0-9]&#x60; regular expression. </param>
        /// <param name="couponPattern">The pattern used to generate coupon codes. The character &#x60;#&#x60; is a placeholder and is replaced by a random character from the &#x60;validCharacters&#x60; set. </param>
        /// <param name="isReservationMandatory">An indication of whether the code can be redeemed only if it has been reserved first. (default to false)</param>
        /// <param name="implicitlyReserved">An indication of whether the coupon is implicitly reserved for all customers.</param>
        [JsonConstructor]
        public NewCoupons(long numberOfCoupons, Option<long?> usageLimit = default, Option<decimal?> discountLimit = default, Option<long?> reservationLimit = default, Option<DateTime?> startDate = default, Option<DateTime?> expiryDate = default, Option<List<LimitConfig>> limits = default, Option<string> uniquePrefix = default, Option<Object> attributes = default, Option<string> recipientIntegrationId = default, Option<List<string>> validCharacters = default, Option<string> couponPattern = default, Option<bool?> isReservationMandatory = default, Option<bool?> implicitlyReserved = default)
        {
            NumberOfCoupons = numberOfCoupons;
            UsageLimitOption = usageLimit;
            DiscountLimitOption = discountLimit;
            ReservationLimitOption = reservationLimit;
            StartDateOption = startDate;
            ExpiryDateOption = expiryDate;
            LimitsOption = limits;
            UniquePrefixOption = uniquePrefix;
            AttributesOption = attributes;
            RecipientIntegrationIdOption = recipientIntegrationId;
            ValidCharactersOption = validCharacters;
            CouponPatternOption = couponPattern;
            IsReservationMandatoryOption = isReservationMandatory;
            ImplicitlyReservedOption = implicitlyReserved;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The number of new coupon codes to generate for the campaign. Must be at least 1.
        /// </summary>
        /// <value>The number of new coupon codes to generate for the campaign. Must be at least 1.</value>
        /* <example>1</example> */
        [JsonPropertyName("numberOfCoupons")]
        public long NumberOfCoupons { get; set; }

        /// <summary>
        /// Used to track the state of UsageLimit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> UsageLimitOption { get; private set; }

        /// <summary>
        /// The number of times the coupon code can be redeemed. &#x60;0&#x60; means unlimited redemptions but any campaign usage limits will still apply. 
        /// </summary>
        /// <value>The number of times the coupon code can be redeemed. &#x60;0&#x60; means unlimited redemptions but any campaign usage limits will still apply. </value>
        /* <example>100</example> */
        [JsonPropertyName("usageLimit")]
        public long? UsageLimit { get { return this.UsageLimitOption; } set { this.UsageLimitOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of DiscountLimit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> DiscountLimitOption { get; private set; }

        /// <summary>
        /// The total discount value that the code can give. Typically used to represent a gift card value. 
        /// </summary>
        /// <value>The total discount value that the code can give. Typically used to represent a gift card value. </value>
        /* <example>30</example> */
        [JsonPropertyName("discountLimit")]
        public decimal? DiscountLimit { get { return this.DiscountLimitOption; } set { this.DiscountLimitOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of ReservationLimit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ReservationLimitOption { get; private set; }

        /// <summary>
        /// The number of reservations that can be made with this coupon code. 
        /// </summary>
        /// <value>The number of reservations that can be made with this coupon code. </value>
        /* <example>45</example> */
        [JsonPropertyName("reservationLimit")]
        public long? ReservationLimit { get { return this.ReservationLimitOption; } set { this.ReservationLimitOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of StartDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartDateOption { get; private set; }

        /// <summary>
        /// Timestamp at which point the coupon becomes valid.
        /// </summary>
        /// <value>Timestamp at which point the coupon becomes valid.</value>
        /* <example>2020-01-24T14:15:22Z</example> */
        [JsonPropertyName("startDate")]
        public DateTime? StartDate { get { return this.StartDateOption; } set { this.StartDateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of ExpiryDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ExpiryDateOption { get; private set; }

        /// <summary>
        /// Expiration date of the coupon. Coupon never expires if this is omitted.
        /// </summary>
        /// <value>Expiration date of the coupon. Coupon never expires if this is omitted.</value>
        /* <example>2023-08-24T14:15:22Z</example> */
        [JsonPropertyName("expiryDate")]
        public DateTime? ExpiryDate { get { return this.ExpiryDateOption; } set { this.ExpiryDateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of Limits
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LimitConfig>> LimitsOption { get; private set; }

        /// <summary>
        /// Limits configuration for a coupon. These limits will override the limits set from the campaign.  **Note:** Only usable when creating a single coupon which is not tied to a specific recipient. Only per-profile limits are allowed to be configured. 
        /// </summary>
        /// <value>Limits configuration for a coupon. These limits will override the limits set from the campaign.  **Note:** Only usable when creating a single coupon which is not tied to a specific recipient. Only per-profile limits are allowed to be configured. </value>
        [JsonPropertyName("limits")]
        public List<LimitConfig> Limits { get { return this.LimitsOption; } set { this.LimitsOption = new Option<List<LimitConfig>>(value); } }

        /// <summary>
        /// Used to track the state of UniquePrefix
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UniquePrefixOption { get; private set; }

        /// <summary>
        /// **DEPRECATED** To create more than 20,000 coupons in one request, use [Create coupons asynchronously](https://docs.talon.one/management-api#operation/createCouponsAsync) endpoint. 
        /// </summary>
        /// <value>**DEPRECATED** To create more than 20,000 coupons in one request, use [Create coupons asynchronously](https://docs.talon.one/management-api#operation/createCouponsAsync) endpoint. </value>
        [JsonPropertyName("uniquePrefix")]
        public string UniquePrefix { get { return this.UniquePrefixOption; } set { this.UniquePrefixOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Attributes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object> AttributesOption { get; private set; }

        /// <summary>
        /// Arbitrary properties associated with this item.
        /// </summary>
        /// <value>Arbitrary properties associated with this item.</value>
        /* <example>{venueId&#x3D;12}</example> */
        [JsonPropertyName("attributes")]
        public Object Attributes { get { return this.AttributesOption; } set { this.AttributesOption = new Option<Object>(value); } }

        /// <summary>
        /// Used to track the state of RecipientIntegrationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RecipientIntegrationIdOption { get; private set; }

        /// <summary>
        /// The integration ID for this coupon&#39;s beneficiary&#39;s profile.
        /// </summary>
        /// <value>The integration ID for this coupon&#39;s beneficiary&#39;s profile.</value>
        /* <example>URNGV8294NV</example> */
        [JsonPropertyName("recipientIntegrationId")]
        public string RecipientIntegrationId { get { return this.RecipientIntegrationIdOption; } set { this.RecipientIntegrationIdOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of ValidCharacters
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> ValidCharactersOption { get; private set; }

        /// <summary>
        /// List of characters used to generate the random parts of a code. By default, the list of characters is equivalent to the &#x60;[A-Z, 0-9]&#x60; regular expression. 
        /// </summary>
        /// <value>List of characters used to generate the random parts of a code. By default, the list of characters is equivalent to the &#x60;[A-Z, 0-9]&#x60; regular expression. </value>
        /* <example>[A, B, G, Y]</example> */
        [JsonPropertyName("validCharacters")]
        public List<string> ValidCharacters { get { return this.ValidCharactersOption; } set { this.ValidCharactersOption = new Option<List<string>>(value); } }

        /// <summary>
        /// Used to track the state of CouponPattern
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CouponPatternOption { get; private set; }

        /// <summary>
        /// The pattern used to generate coupon codes. The character &#x60;#&#x60; is a placeholder and is replaced by a random character from the &#x60;validCharacters&#x60; set. 
        /// </summary>
        /// <value>The pattern used to generate coupon codes. The character &#x60;#&#x60; is a placeholder and is replaced by a random character from the &#x60;validCharacters&#x60; set. </value>
        /* <example>SUMMER-#####</example> */
        [JsonPropertyName("couponPattern")]
        public string CouponPattern { get { return this.CouponPatternOption; } set { this.CouponPatternOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of IsReservationMandatory
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsReservationMandatoryOption { get; private set; }

        /// <summary>
        /// An indication of whether the code can be redeemed only if it has been reserved first.
        /// </summary>
        /// <value>An indication of whether the code can be redeemed only if it has been reserved first.</value>
        /* <example>false</example> */
        [JsonPropertyName("isReservationMandatory")]
        public bool? IsReservationMandatory { get { return this.IsReservationMandatoryOption; } set { this.IsReservationMandatoryOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ImplicitlyReserved
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ImplicitlyReservedOption { get; private set; }

        /// <summary>
        /// An indication of whether the coupon is implicitly reserved for all customers.
        /// </summary>
        /// <value>An indication of whether the coupon is implicitly reserved for all customers.</value>
        /* <example>false</example> */
        [JsonPropertyName("implicitlyReserved")]
        public bool? ImplicitlyReserved { get { return this.ImplicitlyReservedOption; } set { this.ImplicitlyReservedOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NewCoupons {\n");
            sb.Append("  NumberOfCoupons: ").Append(NumberOfCoupons).Append("\n");
            sb.Append("  UsageLimit: ").Append(UsageLimit).Append("\n");
            sb.Append("  DiscountLimit: ").Append(DiscountLimit).Append("\n");
            sb.Append("  ReservationLimit: ").Append(ReservationLimit).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  ExpiryDate: ").Append(ExpiryDate).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  UniquePrefix: ").Append(UniquePrefix).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  RecipientIntegrationId: ").Append(RecipientIntegrationId).Append("\n");
            sb.Append("  ValidCharacters: ").Append(ValidCharacters).Append("\n");
            sb.Append("  CouponPattern: ").Append(CouponPattern).Append("\n");
            sb.Append("  IsReservationMandatory: ").Append(IsReservationMandatory).Append("\n");
            sb.Append("  ImplicitlyReserved: ").Append(ImplicitlyReserved).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // UsageLimit (long) maximum
            if (this.UsageLimitOption.IsSet && this.UsageLimitOption.Value > (long)999999)
            {
                yield return new ValidationResult("Invalid value for UsageLimit, must be a value less than or equal to 999999.", new [] { "UsageLimit" });
            }

            // UsageLimit (long) minimum
            if (this.UsageLimitOption.IsSet && this.UsageLimitOption.Value < (long)0)
            {
                yield return new ValidationResult("Invalid value for UsageLimit, must be a value greater than or equal to 0.", new [] { "UsageLimit" });
            }

            // DiscountLimit (decimal) maximum
            if (this.DiscountLimitOption.IsSet && this.DiscountLimitOption.Value > (decimal)1000000000000000)
            {
                yield return new ValidationResult("Invalid value for DiscountLimit, must be a value less than or equal to 1000000000000000.", new [] { "DiscountLimit" });
            }

            // DiscountLimit (decimal) minimum
            if (this.DiscountLimitOption.IsSet && this.DiscountLimitOption.Value < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for DiscountLimit, must be a value greater than or equal to 0.", new [] { "DiscountLimit" });
            }

            // ReservationLimit (long) maximum
            if (this.ReservationLimitOption.IsSet && this.ReservationLimitOption.Value > (long)999999)
            {
                yield return new ValidationResult("Invalid value for ReservationLimit, must be a value less than or equal to 999999.", new [] { "ReservationLimit" });
            }

            // ReservationLimit (long) minimum
            if (this.ReservationLimitOption.IsSet && this.ReservationLimitOption.Value < (long)0)
            {
                yield return new ValidationResult("Invalid value for ReservationLimit, must be a value greater than or equal to 0.", new [] { "ReservationLimit" });
            }

            // RecipientIntegrationId (string) maxLength
            if (this.RecipientIntegrationId != null && this.RecipientIntegrationId.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for RecipientIntegrationId, length must be less than 1000.", new [] { "RecipientIntegrationId" });
            }

            // CouponPattern (string) maxLength
            if (this.CouponPattern != null && this.CouponPattern.Length > 100)
            {
                yield return new ValidationResult("Invalid value for CouponPattern, length must be less than 100.", new [] { "CouponPattern" });
            }

            // CouponPattern (string) minLength
            if (this.CouponPattern != null && this.CouponPattern.Length < 3)
            {
                yield return new ValidationResult("Invalid value for CouponPattern, length must be greater than 3.", new [] { "CouponPattern" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewCoupons" />
    /// </summary>
    public class NewCouponsJsonConverter : JsonConverter<NewCoupons>
    {
        /// <summary>
        /// The format to use to serialize StartDate
        /// </summary>
        public static string StartDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ExpiryDate
        /// </summary>
        public static string ExpiryDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NewCoupons" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NewCoupons Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> numberOfCoupons = default;
            Option<long?> usageLimit = default;
            Option<decimal?> discountLimit = default;
            Option<long?> reservationLimit = default;
            Option<DateTime?> startDate = default;
            Option<DateTime?> expiryDate = default;
            Option<List<LimitConfig>> limits = default;
            Option<string> uniquePrefix = default;
            Option<Object> attributes = default;
            Option<string> recipientIntegrationId = default;
            Option<List<string>> validCharacters = default;
            Option<string> couponPattern = default;
            Option<bool?> isReservationMandatory = default;
            Option<bool?> implicitlyReserved = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "numberOfCoupons":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                numberOfCoupons = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "usageLimit":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                usageLimit = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "discountLimit":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                discountLimit = new Option<decimal?>(utf8JsonReader.GetDecimal());
                            break;
                        case "reservationLimit":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                reservationLimit = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "startDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                startDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "expiryDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                expiryDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "limits":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                limits = new Option<List<LimitConfig>>(JsonSerializer.Deserialize<List<LimitConfig>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "uniquePrefix":
                            uniquePrefix = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "attributes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                attributes = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "recipientIntegrationId":
                            recipientIntegrationId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "validCharacters":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                validCharacters = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "couponPattern":
                            couponPattern = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "isReservationMandatory":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isReservationMandatory = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "implicitlyReserved":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                implicitlyReserved = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!numberOfCoupons.IsSet)
                throw new ArgumentException("Property is required for class NewCoupons.", nameof(numberOfCoupons));

            if (numberOfCoupons.IsSet && numberOfCoupons.Value == null)
                throw new ArgumentNullException(nameof(numberOfCoupons), "Property is not nullable for class NewCoupons.");

            if (usageLimit.IsSet && usageLimit.Value == null)
                throw new ArgumentNullException(nameof(usageLimit), "Property is not nullable for class NewCoupons.");

            if (discountLimit.IsSet && discountLimit.Value == null)
                throw new ArgumentNullException(nameof(discountLimit), "Property is not nullable for class NewCoupons.");

            if (reservationLimit.IsSet && reservationLimit.Value == null)
                throw new ArgumentNullException(nameof(reservationLimit), "Property is not nullable for class NewCoupons.");

            if (startDate.IsSet && startDate.Value == null)
                throw new ArgumentNullException(nameof(startDate), "Property is not nullable for class NewCoupons.");

            if (expiryDate.IsSet && expiryDate.Value == null)
                throw new ArgumentNullException(nameof(expiryDate), "Property is not nullable for class NewCoupons.");

            if (limits.IsSet && limits.Value == null)
                throw new ArgumentNullException(nameof(limits), "Property is not nullable for class NewCoupons.");

            if (uniquePrefix.IsSet && uniquePrefix.Value == null)
                throw new ArgumentNullException(nameof(uniquePrefix), "Property is not nullable for class NewCoupons.");

            if (attributes.IsSet && attributes.Value == null)
                throw new ArgumentNullException(nameof(attributes), "Property is not nullable for class NewCoupons.");

            if (recipientIntegrationId.IsSet && recipientIntegrationId.Value == null)
                throw new ArgumentNullException(nameof(recipientIntegrationId), "Property is not nullable for class NewCoupons.");

            if (validCharacters.IsSet && validCharacters.Value == null)
                throw new ArgumentNullException(nameof(validCharacters), "Property is not nullable for class NewCoupons.");

            if (couponPattern.IsSet && couponPattern.Value == null)
                throw new ArgumentNullException(nameof(couponPattern), "Property is not nullable for class NewCoupons.");

            if (isReservationMandatory.IsSet && isReservationMandatory.Value == null)
                throw new ArgumentNullException(nameof(isReservationMandatory), "Property is not nullable for class NewCoupons.");

            if (implicitlyReserved.IsSet && implicitlyReserved.Value == null)
                throw new ArgumentNullException(nameof(implicitlyReserved), "Property is not nullable for class NewCoupons.");

            return new NewCoupons(numberOfCoupons.Value.Value, usageLimit, discountLimit, reservationLimit, startDate, expiryDate, limits, uniquePrefix, attributes, recipientIntegrationId, validCharacters, couponPattern, isReservationMandatory, implicitlyReserved);
        }

        /// <summary>
        /// Serializes a <see cref="NewCoupons" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newCoupons"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NewCoupons newCoupons, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, newCoupons, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NewCoupons" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newCoupons"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NewCoupons newCoupons, JsonSerializerOptions jsonSerializerOptions)
        {
            if (newCoupons.LimitsOption.IsSet && newCoupons.Limits == null)
                throw new ArgumentNullException(nameof(newCoupons.Limits), "Property is required for class NewCoupons.");

            if (newCoupons.UniquePrefixOption.IsSet && newCoupons.UniquePrefix == null)
                throw new ArgumentNullException(nameof(newCoupons.UniquePrefix), "Property is required for class NewCoupons.");

            if (newCoupons.AttributesOption.IsSet && newCoupons.Attributes == null)
                throw new ArgumentNullException(nameof(newCoupons.Attributes), "Property is required for class NewCoupons.");

            if (newCoupons.RecipientIntegrationIdOption.IsSet && newCoupons.RecipientIntegrationId == null)
                throw new ArgumentNullException(nameof(newCoupons.RecipientIntegrationId), "Property is required for class NewCoupons.");

            if (newCoupons.ValidCharactersOption.IsSet && newCoupons.ValidCharacters == null)
                throw new ArgumentNullException(nameof(newCoupons.ValidCharacters), "Property is required for class NewCoupons.");

            if (newCoupons.CouponPatternOption.IsSet && newCoupons.CouponPattern == null)
                throw new ArgumentNullException(nameof(newCoupons.CouponPattern), "Property is required for class NewCoupons.");

            writer.WriteNumber("numberOfCoupons", newCoupons.NumberOfCoupons);

            if (newCoupons.UsageLimitOption.IsSet)
                writer.WriteNumber("usageLimit", newCoupons.UsageLimitOption.Value.Value);

            if (newCoupons.DiscountLimitOption.IsSet)
                writer.WriteNumber("discountLimit", newCoupons.DiscountLimitOption.Value.Value);

            if (newCoupons.ReservationLimitOption.IsSet)
                writer.WriteNumber("reservationLimit", newCoupons.ReservationLimitOption.Value.Value);

            if (newCoupons.StartDateOption.IsSet)
                writer.WriteString("startDate", newCoupons.StartDateOption.Value.Value.ToString(StartDateFormat));

            if (newCoupons.ExpiryDateOption.IsSet)
                writer.WriteString("expiryDate", newCoupons.ExpiryDateOption.Value.Value.ToString(ExpiryDateFormat));

            if (newCoupons.LimitsOption.IsSet)
            {
                writer.WritePropertyName("limits");
                JsonSerializer.Serialize(writer, newCoupons.Limits, jsonSerializerOptions);
            }
            if (newCoupons.UniquePrefixOption.IsSet)
                writer.WriteString("uniquePrefix", newCoupons.UniquePrefix);

            if (newCoupons.AttributesOption.IsSet)
            {
                writer.WritePropertyName("attributes");
                JsonSerializer.Serialize(writer, newCoupons.Attributes, jsonSerializerOptions);
            }
            if (newCoupons.RecipientIntegrationIdOption.IsSet)
                writer.WriteString("recipientIntegrationId", newCoupons.RecipientIntegrationId);

            if (newCoupons.ValidCharactersOption.IsSet)
            {
                writer.WritePropertyName("validCharacters");
                JsonSerializer.Serialize(writer, newCoupons.ValidCharacters, jsonSerializerOptions);
            }
            if (newCoupons.CouponPatternOption.IsSet)
                writer.WriteString("couponPattern", newCoupons.CouponPattern);

            if (newCoupons.IsReservationMandatoryOption.IsSet)
                writer.WriteBoolean("isReservationMandatory", newCoupons.IsReservationMandatoryOption.Value.Value);

            if (newCoupons.ImplicitlyReservedOption.IsSet)
                writer.WriteBoolean("implicitlyReserved", newCoupons.ImplicitlyReservedOption.Value.Value);
        }
    }
}
