// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOne.Client;

namespace TalonOne.Model
{
    /// <summary>
    /// The properties specific to the \&quot;triggerWebhook\&quot; effect. This gets triggered whenever a validated rule contained a \&quot;trigger webhook\&quot; effect. This is communicated as an FYI and should usually not require action on your side.
    /// </summary>
    public partial class TriggerWebhookEffectProps : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TriggerWebhookEffectProps" /> class.
        /// </summary>
        /// <param name="webhookId">The ID of the webhook that was triggered.</param>
        /// <param name="webhookName">The name of the webhook that was triggered.</param>
        [JsonConstructor]
        public TriggerWebhookEffectProps(decimal webhookId, string webhookName)
        {
            WebhookId = webhookId;
            WebhookName = webhookName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The ID of the webhook that was triggered.
        /// </summary>
        /// <value>The ID of the webhook that was triggered.</value>
        [JsonPropertyName("webhookId")]
        public decimal WebhookId { get; set; }

        /// <summary>
        /// The name of the webhook that was triggered.
        /// </summary>
        /// <value>The name of the webhook that was triggered.</value>
        [JsonPropertyName("webhookName")]
        public string WebhookName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TriggerWebhookEffectProps {\n");
            sb.Append("  WebhookId: ").Append(WebhookId).Append("\n");
            sb.Append("  WebhookName: ").Append(WebhookName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TriggerWebhookEffectProps" />
    /// </summary>
    public class TriggerWebhookEffectPropsJsonConverter : JsonConverter<TriggerWebhookEffectProps>
    {
        /// <summary>
        /// Deserializes json to <see cref="TriggerWebhookEffectProps" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TriggerWebhookEffectProps Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> webhookId = default;
            Option<string> webhookName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "webhookId":
                            webhookId = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "webhookName":
                            webhookName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!webhookId.IsSet)
                throw new ArgumentException("Property is required for class TriggerWebhookEffectProps.", nameof(webhookId));

            if (!webhookName.IsSet)
                throw new ArgumentException("Property is required for class TriggerWebhookEffectProps.", nameof(webhookName));

            if (webhookId.IsSet && webhookId.Value == null)
                throw new ArgumentNullException(nameof(webhookId), "Property is not nullable for class TriggerWebhookEffectProps.");

            if (webhookName.IsSet && webhookName.Value == null)
                throw new ArgumentNullException(nameof(webhookName), "Property is not nullable for class TriggerWebhookEffectProps.");

            return new TriggerWebhookEffectProps(webhookId.Value.Value, webhookName.Value);
        }

        /// <summary>
        /// Serializes a <see cref="TriggerWebhookEffectProps" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="triggerWebhookEffectProps"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TriggerWebhookEffectProps triggerWebhookEffectProps, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, triggerWebhookEffectProps, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TriggerWebhookEffectProps" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="triggerWebhookEffectProps"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TriggerWebhookEffectProps triggerWebhookEffectProps, JsonSerializerOptions jsonSerializerOptions)
        {
            if (triggerWebhookEffectProps.WebhookName == null)
                throw new ArgumentNullException(nameof(triggerWebhookEffectProps.WebhookName), "Property is required for class TriggerWebhookEffectProps.");

            writer.WriteNumber("webhookId", triggerWebhookEffectProps.WebhookId);

            writer.WriteString("webhookName", triggerWebhookEffectProps.WebhookName);
        }
    }
}
