// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// AccountAnalytics
    /// </summary>
    public partial class AccountAnalytics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountAnalytics" /> class.
        /// </summary>
        /// <param name="applications">Total number of applications in the account.</param>
        /// <param name="liveApplications">Total number of live applications in the account.</param>
        /// <param name="sandboxApplications">Total number of sandbox applications in the account.</param>
        /// <param name="campaigns">Total number of campaigns in the account.</param>
        /// <param name="activeCampaigns">Total number of active campaigns in the account.</param>
        /// <param name="liveActiveCampaigns">Total number of active campaigns in live applications in the account.</param>
        /// <param name="coupons">Total number of coupons in the account.</param>
        /// <param name="activeCoupons">Total number of active coupons in the account.</param>
        /// <param name="expiredCoupons">Total number of expired coupons in the account.</param>
        /// <param name="referralCodes">Total number of referral codes in the account.</param>
        /// <param name="activeReferralCodes">Total number of active referral codes in the account.</param>
        /// <param name="expiredReferralCodes">Total number of expired referral codes in the account.</param>
        /// <param name="activeRules">Total number of active rules in the account.</param>
        /// <param name="users">Total number of users in the account.</param>
        /// <param name="roles">Total number of roles in the account.</param>
        /// <param name="customAttributes">Total number of custom attributes in the account.</param>
        /// <param name="webhooks">Total number of webhooks in the account.</param>
        /// <param name="loyaltyPrograms">Total number of all loyalty programs in the account.</param>
        /// <param name="liveLoyaltyPrograms">Total number of live loyalty programs in the account.</param>
        /// <param name="lastUpdatedAt">The point in time when the analytics numbers were updated last.</param>
        [JsonConstructor]
        public AccountAnalytics(long applications, long liveApplications, long sandboxApplications, long campaigns, long activeCampaigns, long liveActiveCampaigns, long coupons, long activeCoupons, long expiredCoupons, long referralCodes, long activeReferralCodes, long expiredReferralCodes, long activeRules, long users, long roles, long customAttributes, long webhooks, long loyaltyPrograms, long liveLoyaltyPrograms, DateTime lastUpdatedAt)
        {
            Applications = applications;
            LiveApplications = liveApplications;
            SandboxApplications = sandboxApplications;
            Campaigns = campaigns;
            ActiveCampaigns = activeCampaigns;
            LiveActiveCampaigns = liveActiveCampaigns;
            Coupons = coupons;
            ActiveCoupons = activeCoupons;
            ExpiredCoupons = expiredCoupons;
            ReferralCodes = referralCodes;
            ActiveReferralCodes = activeReferralCodes;
            ExpiredReferralCodes = expiredReferralCodes;
            ActiveRules = activeRules;
            Users = users;
            Roles = roles;
            CustomAttributes = customAttributes;
            Webhooks = webhooks;
            LoyaltyPrograms = loyaltyPrograms;
            LiveLoyaltyPrograms = liveLoyaltyPrograms;
            LastUpdatedAt = lastUpdatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Total number of applications in the account.
        /// </summary>
        /// <value>Total number of applications in the account.</value>
        /* <example>11</example> */
        [JsonPropertyName("applications")]
        public long Applications { get; set; }

        /// <summary>
        /// Total number of live applications in the account.
        /// </summary>
        /// <value>Total number of live applications in the account.</value>
        /* <example>6</example> */
        [JsonPropertyName("liveApplications")]
        public long LiveApplications { get; set; }

        /// <summary>
        /// Total number of sandbox applications in the account.
        /// </summary>
        /// <value>Total number of sandbox applications in the account.</value>
        /* <example>2</example> */
        [JsonPropertyName("sandboxApplications")]
        public long SandboxApplications { get; set; }

        /// <summary>
        /// Total number of campaigns in the account.
        /// </summary>
        /// <value>Total number of campaigns in the account.</value>
        /* <example>35</example> */
        [JsonPropertyName("campaigns")]
        public long Campaigns { get; set; }

        /// <summary>
        /// Total number of active campaigns in the account.
        /// </summary>
        /// <value>Total number of active campaigns in the account.</value>
        /* <example>15</example> */
        [JsonPropertyName("activeCampaigns")]
        public long ActiveCampaigns { get; set; }

        /// <summary>
        /// Total number of active campaigns in live applications in the account.
        /// </summary>
        /// <value>Total number of active campaigns in live applications in the account.</value>
        /* <example>10</example> */
        [JsonPropertyName("liveActiveCampaigns")]
        public long LiveActiveCampaigns { get; set; }

        /// <summary>
        /// Total number of coupons in the account.
        /// </summary>
        /// <value>Total number of coupons in the account.</value>
        /* <example>850</example> */
        [JsonPropertyName("coupons")]
        public long Coupons { get; set; }

        /// <summary>
        /// Total number of active coupons in the account.
        /// </summary>
        /// <value>Total number of active coupons in the account.</value>
        /* <example>650</example> */
        [JsonPropertyName("activeCoupons")]
        public long ActiveCoupons { get; set; }

        /// <summary>
        /// Total number of expired coupons in the account.
        /// </summary>
        /// <value>Total number of expired coupons in the account.</value>
        /* <example>200</example> */
        [JsonPropertyName("expiredCoupons")]
        public long ExpiredCoupons { get; set; }

        /// <summary>
        /// Total number of referral codes in the account.
        /// </summary>
        /// <value>Total number of referral codes in the account.</value>
        /* <example>500</example> */
        [JsonPropertyName("referralCodes")]
        public long ReferralCodes { get; set; }

        /// <summary>
        /// Total number of active referral codes in the account.
        /// </summary>
        /// <value>Total number of active referral codes in the account.</value>
        /* <example>100</example> */
        [JsonPropertyName("activeReferralCodes")]
        public long ActiveReferralCodes { get; set; }

        /// <summary>
        /// Total number of expired referral codes in the account.
        /// </summary>
        /// <value>Total number of expired referral codes in the account.</value>
        /* <example>400</example> */
        [JsonPropertyName("expiredReferralCodes")]
        public long ExpiredReferralCodes { get; set; }

        /// <summary>
        /// Total number of active rules in the account.
        /// </summary>
        /// <value>Total number of active rules in the account.</value>
        /* <example>35</example> */
        [JsonPropertyName("activeRules")]
        public long ActiveRules { get; set; }

        /// <summary>
        /// Total number of users in the account.
        /// </summary>
        /// <value>Total number of users in the account.</value>
        [JsonPropertyName("users")]
        public long Users { get; set; }

        /// <summary>
        /// Total number of roles in the account.
        /// </summary>
        /// <value>Total number of roles in the account.</value>
        /* <example>10</example> */
        [JsonPropertyName("roles")]
        public long Roles { get; set; }

        /// <summary>
        /// Total number of custom attributes in the account.
        /// </summary>
        /// <value>Total number of custom attributes in the account.</value>
        /* <example>18</example> */
        [JsonPropertyName("customAttributes")]
        public long CustomAttributes { get; set; }

        /// <summary>
        /// Total number of webhooks in the account.
        /// </summary>
        /// <value>Total number of webhooks in the account.</value>
        /* <example>2</example> */
        [JsonPropertyName("webhooks")]
        public long Webhooks { get; set; }

        /// <summary>
        /// Total number of all loyalty programs in the account.
        /// </summary>
        /// <value>Total number of all loyalty programs in the account.</value>
        /* <example>5</example> */
        [JsonPropertyName("loyaltyPrograms")]
        public long LoyaltyPrograms { get; set; }

        /// <summary>
        /// Total number of live loyalty programs in the account.
        /// </summary>
        /// <value>Total number of live loyalty programs in the account.</value>
        /* <example>5</example> */
        [JsonPropertyName("liveLoyaltyPrograms")]
        public long LiveLoyaltyPrograms { get; set; }

        /// <summary>
        /// The point in time when the analytics numbers were updated last.
        /// </summary>
        /// <value>The point in time when the analytics numbers were updated last.</value>
        /* <example>2022-12-12T12:12:12Z</example> */
        [JsonPropertyName("lastUpdatedAt")]
        public DateTime LastUpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountAnalytics {\n");
            sb.Append("  Applications: ").Append(Applications).Append("\n");
            sb.Append("  LiveApplications: ").Append(LiveApplications).Append("\n");
            sb.Append("  SandboxApplications: ").Append(SandboxApplications).Append("\n");
            sb.Append("  Campaigns: ").Append(Campaigns).Append("\n");
            sb.Append("  ActiveCampaigns: ").Append(ActiveCampaigns).Append("\n");
            sb.Append("  LiveActiveCampaigns: ").Append(LiveActiveCampaigns).Append("\n");
            sb.Append("  Coupons: ").Append(Coupons).Append("\n");
            sb.Append("  ActiveCoupons: ").Append(ActiveCoupons).Append("\n");
            sb.Append("  ExpiredCoupons: ").Append(ExpiredCoupons).Append("\n");
            sb.Append("  ReferralCodes: ").Append(ReferralCodes).Append("\n");
            sb.Append("  ActiveReferralCodes: ").Append(ActiveReferralCodes).Append("\n");
            sb.Append("  ExpiredReferralCodes: ").Append(ExpiredReferralCodes).Append("\n");
            sb.Append("  ActiveRules: ").Append(ActiveRules).Append("\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("  CustomAttributes: ").Append(CustomAttributes).Append("\n");
            sb.Append("  Webhooks: ").Append(Webhooks).Append("\n");
            sb.Append("  LoyaltyPrograms: ").Append(LoyaltyPrograms).Append("\n");
            sb.Append("  LiveLoyaltyPrograms: ").Append(LiveLoyaltyPrograms).Append("\n");
            sb.Append("  LastUpdatedAt: ").Append(LastUpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AccountAnalytics" />
    /// </summary>
    public class AccountAnalyticsJsonConverter : JsonConverter<AccountAnalytics>
    {
        /// <summary>
        /// The format to use to serialize LastUpdatedAt
        /// </summary>
        public static string LastUpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="AccountAnalytics" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AccountAnalytics Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> applications = default;
            Option<long?> liveApplications = default;
            Option<long?> sandboxApplications = default;
            Option<long?> campaigns = default;
            Option<long?> activeCampaigns = default;
            Option<long?> liveActiveCampaigns = default;
            Option<long?> coupons = default;
            Option<long?> activeCoupons = default;
            Option<long?> expiredCoupons = default;
            Option<long?> referralCodes = default;
            Option<long?> activeReferralCodes = default;
            Option<long?> expiredReferralCodes = default;
            Option<long?> activeRules = default;
            Option<long?> users = default;
            Option<long?> roles = default;
            Option<long?> customAttributes = default;
            Option<long?> webhooks = default;
            Option<long?> loyaltyPrograms = default;
            Option<long?> liveLoyaltyPrograms = default;
            Option<DateTime?> lastUpdatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "applications":
                            applications = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "liveApplications":
                            liveApplications = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "sandboxApplications":
                            sandboxApplications = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "campaigns":
                            campaigns = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "activeCampaigns":
                            activeCampaigns = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "liveActiveCampaigns":
                            liveActiveCampaigns = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "coupons":
                            coupons = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "activeCoupons":
                            activeCoupons = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "expiredCoupons":
                            expiredCoupons = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "referralCodes":
                            referralCodes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "activeReferralCodes":
                            activeReferralCodes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "expiredReferralCodes":
                            expiredReferralCodes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "activeRules":
                            activeRules = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "users":
                            users = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "roles":
                            roles = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "customAttributes":
                            customAttributes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "webhooks":
                            webhooks = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "loyaltyPrograms":
                            loyaltyPrograms = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "liveLoyaltyPrograms":
                            liveLoyaltyPrograms = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "lastUpdatedAt":
                            lastUpdatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!applications.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(applications));

            if (!liveApplications.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(liveApplications));

            if (!sandboxApplications.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(sandboxApplications));

            if (!campaigns.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(campaigns));

            if (!activeCampaigns.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(activeCampaigns));

            if (!liveActiveCampaigns.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(liveActiveCampaigns));

            if (!coupons.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(coupons));

            if (!activeCoupons.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(activeCoupons));

            if (!expiredCoupons.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(expiredCoupons));

            if (!referralCodes.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(referralCodes));

            if (!activeReferralCodes.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(activeReferralCodes));

            if (!expiredReferralCodes.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(expiredReferralCodes));

            if (!activeRules.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(activeRules));

            if (!users.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(users));

            if (!roles.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(roles));

            if (!customAttributes.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(customAttributes));

            if (!webhooks.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(webhooks));

            if (!loyaltyPrograms.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(loyaltyPrograms));

            if (!liveLoyaltyPrograms.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(liveLoyaltyPrograms));

            if (!lastUpdatedAt.IsSet)
                throw new ArgumentException("Property is required for class AccountAnalytics.", nameof(lastUpdatedAt));

            if (applications.IsSet && applications.Value == null)
                throw new ArgumentNullException(nameof(applications), "Property is not nullable for class AccountAnalytics.");

            if (liveApplications.IsSet && liveApplications.Value == null)
                throw new ArgumentNullException(nameof(liveApplications), "Property is not nullable for class AccountAnalytics.");

            if (sandboxApplications.IsSet && sandboxApplications.Value == null)
                throw new ArgumentNullException(nameof(sandboxApplications), "Property is not nullable for class AccountAnalytics.");

            if (campaigns.IsSet && campaigns.Value == null)
                throw new ArgumentNullException(nameof(campaigns), "Property is not nullable for class AccountAnalytics.");

            if (activeCampaigns.IsSet && activeCampaigns.Value == null)
                throw new ArgumentNullException(nameof(activeCampaigns), "Property is not nullable for class AccountAnalytics.");

            if (liveActiveCampaigns.IsSet && liveActiveCampaigns.Value == null)
                throw new ArgumentNullException(nameof(liveActiveCampaigns), "Property is not nullable for class AccountAnalytics.");

            if (coupons.IsSet && coupons.Value == null)
                throw new ArgumentNullException(nameof(coupons), "Property is not nullable for class AccountAnalytics.");

            if (activeCoupons.IsSet && activeCoupons.Value == null)
                throw new ArgumentNullException(nameof(activeCoupons), "Property is not nullable for class AccountAnalytics.");

            if (expiredCoupons.IsSet && expiredCoupons.Value == null)
                throw new ArgumentNullException(nameof(expiredCoupons), "Property is not nullable for class AccountAnalytics.");

            if (referralCodes.IsSet && referralCodes.Value == null)
                throw new ArgumentNullException(nameof(referralCodes), "Property is not nullable for class AccountAnalytics.");

            if (activeReferralCodes.IsSet && activeReferralCodes.Value == null)
                throw new ArgumentNullException(nameof(activeReferralCodes), "Property is not nullable for class AccountAnalytics.");

            if (expiredReferralCodes.IsSet && expiredReferralCodes.Value == null)
                throw new ArgumentNullException(nameof(expiredReferralCodes), "Property is not nullable for class AccountAnalytics.");

            if (activeRules.IsSet && activeRules.Value == null)
                throw new ArgumentNullException(nameof(activeRules), "Property is not nullable for class AccountAnalytics.");

            if (users.IsSet && users.Value == null)
                throw new ArgumentNullException(nameof(users), "Property is not nullable for class AccountAnalytics.");

            if (roles.IsSet && roles.Value == null)
                throw new ArgumentNullException(nameof(roles), "Property is not nullable for class AccountAnalytics.");

            if (customAttributes.IsSet && customAttributes.Value == null)
                throw new ArgumentNullException(nameof(customAttributes), "Property is not nullable for class AccountAnalytics.");

            if (webhooks.IsSet && webhooks.Value == null)
                throw new ArgumentNullException(nameof(webhooks), "Property is not nullable for class AccountAnalytics.");

            if (loyaltyPrograms.IsSet && loyaltyPrograms.Value == null)
                throw new ArgumentNullException(nameof(loyaltyPrograms), "Property is not nullable for class AccountAnalytics.");

            if (liveLoyaltyPrograms.IsSet && liveLoyaltyPrograms.Value == null)
                throw new ArgumentNullException(nameof(liveLoyaltyPrograms), "Property is not nullable for class AccountAnalytics.");

            if (lastUpdatedAt.IsSet && lastUpdatedAt.Value == null)
                throw new ArgumentNullException(nameof(lastUpdatedAt), "Property is not nullable for class AccountAnalytics.");

            return new AccountAnalytics(applications.Value.Value, liveApplications.Value.Value, sandboxApplications.Value.Value, campaigns.Value.Value, activeCampaigns.Value.Value, liveActiveCampaigns.Value.Value, coupons.Value.Value, activeCoupons.Value.Value, expiredCoupons.Value.Value, referralCodes.Value.Value, activeReferralCodes.Value.Value, expiredReferralCodes.Value.Value, activeRules.Value.Value, users.Value.Value, roles.Value.Value, customAttributes.Value.Value, webhooks.Value.Value, loyaltyPrograms.Value.Value, liveLoyaltyPrograms.Value.Value, lastUpdatedAt.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="AccountAnalytics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountAnalytics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AccountAnalytics accountAnalytics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, accountAnalytics, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AccountAnalytics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountAnalytics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AccountAnalytics accountAnalytics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("applications", accountAnalytics.Applications);

            writer.WriteNumber("liveApplications", accountAnalytics.LiveApplications);

            writer.WriteNumber("sandboxApplications", accountAnalytics.SandboxApplications);

            writer.WriteNumber("campaigns", accountAnalytics.Campaigns);

            writer.WriteNumber("activeCampaigns", accountAnalytics.ActiveCampaigns);

            writer.WriteNumber("liveActiveCampaigns", accountAnalytics.LiveActiveCampaigns);

            writer.WriteNumber("coupons", accountAnalytics.Coupons);

            writer.WriteNumber("activeCoupons", accountAnalytics.ActiveCoupons);

            writer.WriteNumber("expiredCoupons", accountAnalytics.ExpiredCoupons);

            writer.WriteNumber("referralCodes", accountAnalytics.ReferralCodes);

            writer.WriteNumber("activeReferralCodes", accountAnalytics.ActiveReferralCodes);

            writer.WriteNumber("expiredReferralCodes", accountAnalytics.ExpiredReferralCodes);

            writer.WriteNumber("activeRules", accountAnalytics.ActiveRules);

            writer.WriteNumber("users", accountAnalytics.Users);

            writer.WriteNumber("roles", accountAnalytics.Roles);

            writer.WriteNumber("customAttributes", accountAnalytics.CustomAttributes);

            writer.WriteNumber("webhooks", accountAnalytics.Webhooks);

            writer.WriteNumber("loyaltyPrograms", accountAnalytics.LoyaltyPrograms);

            writer.WriteNumber("liveLoyaltyPrograms", accountAnalytics.LiveLoyaltyPrograms);

            writer.WriteString("lastUpdatedAt", accountAnalytics.LastUpdatedAt.ToString(LastUpdatedAtFormat));
        }
    }
}
