// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// AchievementAdditionalPropertiesV2
    /// </summary>
    public partial class AchievementAdditionalPropertiesV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AchievementAdditionalPropertiesV2" /> class.
        /// </summary>
        /// <param name="userId">The ID of the user that created this achievement.</param>
        /// <param name="createdBy">Name of the user that created the achievement.  **Note**: This is not available if the user has been deleted. </param>
        /// <param name="hasProgress">Indicates if a customer has made progress in the achievement.</param>
        /// <param name="status">The status of the achievement.</param>
        [JsonConstructor]
        public AchievementAdditionalPropertiesV2(long userId, Option<string> createdBy = default, Option<bool?> hasProgress = default, Option<StatusEnum?> status = default)
        {
            UserId = userId;
            CreatedByOption = createdBy;
            HasProgressOption = hasProgress;
            StatusOption = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The status of the achievement.
        /// </summary>
        /// <value>The status of the achievement.</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Inprogress for value: inprogress
            /// </summary>
            Inprogress = 1,

            /// <summary>
            /// Enum Expired for value: expired
            /// </summary>
            Expired = 2,

            /// <summary>
            /// Enum NotStarted for value: not_started
            /// </summary>
            NotStarted = 3,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            Completed = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("inprogress"))
                return StatusEnum.Inprogress;

            if (value.Equals("expired"))
                return StatusEnum.Expired;

            if (value.Equals("not_started"))
                return StatusEnum.NotStarted;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("inprogress"))
                return StatusEnum.Inprogress;

            if (value.Equals("expired"))
                return StatusEnum.Expired;

            if (value.Equals("not_started"))
                return StatusEnum.NotStarted;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Inprogress)
                return "inprogress";

            if (value == StatusEnum.Expired)
                return "expired";

            if (value == StatusEnum.NotStarted)
                return "not_started";

            if (value == StatusEnum.Completed)
                return "completed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// The status of the achievement.
        /// </summary>
        /// <value>The status of the achievement.</value>
        /* <example>inprogress</example> */
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new Option<StatusEnum?>(value); } }

        /// <summary>
        /// The ID of the user that created this achievement.
        /// </summary>
        /// <value>The ID of the user that created this achievement.</value>
        /* <example>1234</example> */
        [JsonPropertyName("userId")]
        public long UserId { get; set; }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CreatedByOption { get; private set; }

        /// <summary>
        /// Name of the user that created the achievement.  **Note**: This is not available if the user has been deleted. 
        /// </summary>
        /// <value>Name of the user that created the achievement.  **Note**: This is not available if the user has been deleted. </value>
        /* <example>John Doe</example> */
        [JsonPropertyName("createdBy")]
        public string CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of HasProgress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasProgressOption { get; private set; }

        /// <summary>
        /// Indicates if a customer has made progress in the achievement.
        /// </summary>
        /// <value>Indicates if a customer has made progress in the achievement.</value>
        [JsonPropertyName("hasProgress")]
        public bool? HasProgress { get { return this.HasProgressOption; } set { this.HasProgressOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AchievementAdditionalPropertiesV2 {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  HasProgress: ").Append(HasProgress).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AchievementAdditionalPropertiesV2" />
    /// </summary>
    public class AchievementAdditionalPropertiesV2JsonConverter : JsonConverter<AchievementAdditionalPropertiesV2>
    {
        /// <summary>
        /// Deserializes json to <see cref="AchievementAdditionalPropertiesV2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AchievementAdditionalPropertiesV2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> userId = default;
            Option<string> createdBy = default;
            Option<bool?> hasProgress = default;
            Option<AchievementAdditionalPropertiesV2.StatusEnum?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "userId":
                            userId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "createdBy":
                            createdBy = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "hasProgress":
                            hasProgress = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "status":
                            string statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<AchievementAdditionalPropertiesV2.StatusEnum?>(AchievementAdditionalPropertiesV2.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class AchievementAdditionalPropertiesV2.", nameof(userId));

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class AchievementAdditionalPropertiesV2.");

            if (createdBy.IsSet && createdBy.Value == null)
                throw new ArgumentNullException(nameof(createdBy), "Property is not nullable for class AchievementAdditionalPropertiesV2.");

            if (hasProgress.IsSet && hasProgress.Value == null)
                throw new ArgumentNullException(nameof(hasProgress), "Property is not nullable for class AchievementAdditionalPropertiesV2.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class AchievementAdditionalPropertiesV2.");

            return new AchievementAdditionalPropertiesV2(userId.Value.Value, createdBy, hasProgress, status);
        }

        /// <summary>
        /// Serializes a <see cref="AchievementAdditionalPropertiesV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="achievementAdditionalPropertiesV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AchievementAdditionalPropertiesV2 achievementAdditionalPropertiesV2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, achievementAdditionalPropertiesV2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AchievementAdditionalPropertiesV2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="achievementAdditionalPropertiesV2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AchievementAdditionalPropertiesV2 achievementAdditionalPropertiesV2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (achievementAdditionalPropertiesV2.CreatedByOption.IsSet && achievementAdditionalPropertiesV2.CreatedBy == null)
                throw new ArgumentNullException(nameof(achievementAdditionalPropertiesV2.CreatedBy), "Property is required for class AchievementAdditionalPropertiesV2.");

            writer.WriteNumber("userId", achievementAdditionalPropertiesV2.UserId);

            if (achievementAdditionalPropertiesV2.CreatedByOption.IsSet)
                writer.WriteString("createdBy", achievementAdditionalPropertiesV2.CreatedBy);

            if (achievementAdditionalPropertiesV2.HasProgressOption.IsSet)
                writer.WriteBoolean("hasProgress", achievementAdditionalPropertiesV2.HasProgressOption.Value.Value);

            if (achievementAdditionalPropertiesV2.StatusOption.IsSet)
            {
                var statusRawValue = AchievementAdditionalPropertiesV2.StatusEnumToJsonValue(achievementAdditionalPropertiesV2.StatusOption.Value);
                writer.WriteString("status", statusRawValue);
            }
        }
    }
}
