// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// Report of health of the API connection of an application.
    /// </summary>
    public partial class ApplicationApiHealth : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationApiHealth" /> class.
        /// </summary>
        /// <param name="summary">One-word summary of the health of the API connection of an application. Possible values are: - &#x60;OK&#x60;: The Application has received only successful API requests in the last 5 minutes. - &#x60;WARNING&#x60;: The Application received at least one failed request in the last 50 minutes. - &#x60;ERROR&#x60;: More than 50% of received requests failed. - &#x60;CRITICAL&#x60;: All received requests failed. - &#x60;NONE&#x60;: During the last 5 minutes, the Application hasn&#39;t recorded any integration API requests. </param>
        /// <param name="lastUsed">time of last request relevant to the API health test.</param>
        [JsonConstructor]
        public ApplicationApiHealth(SummaryEnum summary, DateTime lastUsed)
        {
            Summary = summary;
            LastUsed = lastUsed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// One-word summary of the health of the API connection of an application. Possible values are: - &#x60;OK&#x60;: The Application has received only successful API requests in the last 5 minutes. - &#x60;WARNING&#x60;: The Application received at least one failed request in the last 50 minutes. - &#x60;ERROR&#x60;: More than 50% of received requests failed. - &#x60;CRITICAL&#x60;: All received requests failed. - &#x60;NONE&#x60;: During the last 5 minutes, the Application hasn&#39;t recorded any integration API requests. 
        /// </summary>
        /// <value>One-word summary of the health of the API connection of an application. Possible values are: - &#x60;OK&#x60;: The Application has received only successful API requests in the last 5 minutes. - &#x60;WARNING&#x60;: The Application received at least one failed request in the last 50 minutes. - &#x60;ERROR&#x60;: More than 50% of received requests failed. - &#x60;CRITICAL&#x60;: All received requests failed. - &#x60;NONE&#x60;: During the last 5 minutes, the Application hasn&#39;t recorded any integration API requests. </value>
        public enum SummaryEnum
        {
            /// <summary>
            /// Enum OK for value: OK
            /// </summary>
            OK = 1,

            /// <summary>
            /// Enum WARNING for value: WARNING
            /// </summary>
            WARNING = 2,

            /// <summary>
            /// Enum ERROR for value: ERROR
            /// </summary>
            ERROR = 3,

            /// <summary>
            /// Enum CRITICAL for value: CRITICAL
            /// </summary>
            CRITICAL = 4,

            /// <summary>
            /// Enum NONE for value: NONE
            /// </summary>
            NONE = 5
        }

        /// <summary>
        /// Returns a <see cref="SummaryEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SummaryEnum SummaryEnumFromString(string value)
        {
            if (value.Equals("OK"))
                return SummaryEnum.OK;

            if (value.Equals("WARNING"))
                return SummaryEnum.WARNING;

            if (value.Equals("ERROR"))
                return SummaryEnum.ERROR;

            if (value.Equals("CRITICAL"))
                return SummaryEnum.CRITICAL;

            if (value.Equals("NONE"))
                return SummaryEnum.NONE;

            throw new NotImplementedException($"Could not convert value to type SummaryEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SummaryEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SummaryEnum? SummaryEnumFromStringOrDefault(string value)
        {
            if (value.Equals("OK"))
                return SummaryEnum.OK;

            if (value.Equals("WARNING"))
                return SummaryEnum.WARNING;

            if (value.Equals("ERROR"))
                return SummaryEnum.ERROR;

            if (value.Equals("CRITICAL"))
                return SummaryEnum.CRITICAL;

            if (value.Equals("NONE"))
                return SummaryEnum.NONE;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SummaryEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SummaryEnumToJsonValue(SummaryEnum value)
        {
            if (value == SummaryEnum.OK)
                return "OK";

            if (value == SummaryEnum.WARNING)
                return "WARNING";

            if (value == SummaryEnum.ERROR)
                return "ERROR";

            if (value == SummaryEnum.CRITICAL)
                return "CRITICAL";

            if (value == SummaryEnum.NONE)
                return "NONE";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// One-word summary of the health of the API connection of an application. Possible values are: - &#x60;OK&#x60;: The Application has received only successful API requests in the last 5 minutes. - &#x60;WARNING&#x60;: The Application received at least one failed request in the last 50 minutes. - &#x60;ERROR&#x60;: More than 50% of received requests failed. - &#x60;CRITICAL&#x60;: All received requests failed. - &#x60;NONE&#x60;: During the last 5 minutes, the Application hasn&#39;t recorded any integration API requests. 
        /// </summary>
        /// <value>One-word summary of the health of the API connection of an application. Possible values are: - &#x60;OK&#x60;: The Application has received only successful API requests in the last 5 minutes. - &#x60;WARNING&#x60;: The Application received at least one failed request in the last 50 minutes. - &#x60;ERROR&#x60;: More than 50% of received requests failed. - &#x60;CRITICAL&#x60;: All received requests failed. - &#x60;NONE&#x60;: During the last 5 minutes, the Application hasn&#39;t recorded any integration API requests. </value>
        [JsonPropertyName("summary")]
        public SummaryEnum Summary { get; set; }

        /// <summary>
        /// time of last request relevant to the API health test.
        /// </summary>
        /// <value>time of last request relevant to the API health test.</value>
        /* <example>2021-09-12T10:12:42Z</example> */
        [JsonPropertyName("lastUsed")]
        public DateTime LastUsed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplicationApiHealth {\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  LastUsed: ").Append(LastUsed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApplicationApiHealth" />
    /// </summary>
    public class ApplicationApiHealthJsonConverter : JsonConverter<ApplicationApiHealth>
    {
        /// <summary>
        /// The format to use to serialize LastUsed
        /// </summary>
        public static string LastUsedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ApplicationApiHealth" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApplicationApiHealth Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ApplicationApiHealth.SummaryEnum?> summary = default;
            Option<DateTime?> lastUsed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "summary":
                            string summaryRawValue = utf8JsonReader.GetString();
                            if (summaryRawValue != null)
                                summary = new Option<ApplicationApiHealth.SummaryEnum?>(ApplicationApiHealth.SummaryEnumFromStringOrDefault(summaryRawValue));
                            break;
                        case "lastUsed":
                            lastUsed = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!summary.IsSet)
                throw new ArgumentException("Property is required for class ApplicationApiHealth.", nameof(summary));

            if (!lastUsed.IsSet)
                throw new ArgumentException("Property is required for class ApplicationApiHealth.", nameof(lastUsed));

            if (summary.IsSet && summary.Value == null)
                throw new ArgumentNullException(nameof(summary), "Property is not nullable for class ApplicationApiHealth.");

            if (lastUsed.IsSet && lastUsed.Value == null)
                throw new ArgumentNullException(nameof(lastUsed), "Property is not nullable for class ApplicationApiHealth.");

            return new ApplicationApiHealth(summary.Value.Value, lastUsed.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="ApplicationApiHealth" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="applicationApiHealth"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApplicationApiHealth applicationApiHealth, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, applicationApiHealth, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApplicationApiHealth" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="applicationApiHealth"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApplicationApiHealth applicationApiHealth, JsonSerializerOptions jsonSerializerOptions)
        {
            var summaryRawValue = ApplicationApiHealth.SummaryEnumToJsonValue(applicationApiHealth.Summary);
            writer.WriteString("summary", summaryRawValue);
            writer.WriteString("lastUsed", applicationApiHealth.LastUsed.ToString(LastUsedFormat));
        }
    }
}
