// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// EffectSetDiscountPerAdditionalCost
    /// </summary>
    public partial class EffectSetDiscountPerAdditionalCost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EffectSetDiscountPerAdditionalCost" /> class.
        /// </summary>
        /// <param name="effectType">An effect discriminator of type &#x60;setDiscountPerAdditionalCost&#x60;.</param>
        /// <param name="props">The properties of the &#x60;setDiscountPerAdditionalCost&#x60; effect.</param>
        [JsonConstructor]
        public EffectSetDiscountPerAdditionalCost(EffectTypeEnum effectType, SetDiscountPerAdditionalCostEffectProps props)
        {
            EffectType = effectType;
            Props = props;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// An effect discriminator of type &#x60;setDiscountPerAdditionalCost&#x60;.
        /// </summary>
        /// <value>An effect discriminator of type &#x60;setDiscountPerAdditionalCost&#x60;.</value>
        public enum EffectTypeEnum
        {
            /// <summary>
            /// Enum SetDiscountPerAdditionalCost for value: setDiscountPerAdditionalCost
            /// </summary>
            SetDiscountPerAdditionalCost = 1
        }

        /// <summary>
        /// Returns a <see cref="EffectTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EffectTypeEnum EffectTypeEnumFromString(string value)
        {
            if (value.Equals("setDiscountPerAdditionalCost"))
                return EffectTypeEnum.SetDiscountPerAdditionalCost;

            throw new NotImplementedException($"Could not convert value to type EffectTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EffectTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EffectTypeEnum? EffectTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("setDiscountPerAdditionalCost"))
                return EffectTypeEnum.SetDiscountPerAdditionalCost;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EffectTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EffectTypeEnumToJsonValue(EffectTypeEnum value)
        {
            if (value == EffectTypeEnum.SetDiscountPerAdditionalCost)
                return "setDiscountPerAdditionalCost";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// An effect discriminator of type &#x60;setDiscountPerAdditionalCost&#x60;.
        /// </summary>
        /// <value>An effect discriminator of type &#x60;setDiscountPerAdditionalCost&#x60;.</value>
        [JsonPropertyName("effectType")]
        public EffectTypeEnum EffectType { get; set; }

        /// <summary>
        /// The properties of the &#x60;setDiscountPerAdditionalCost&#x60; effect.
        /// </summary>
        /// <value>The properties of the &#x60;setDiscountPerAdditionalCost&#x60; effect.</value>
        [JsonPropertyName("props")]
        public SetDiscountPerAdditionalCostEffectProps Props { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EffectSetDiscountPerAdditionalCost {\n");
            sb.Append("  EffectType: ").Append(EffectType).Append("\n");
            sb.Append("  Props: ").Append(Props).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EffectSetDiscountPerAdditionalCost" />
    /// </summary>
    public partial class EffectSetDiscountPerAdditionalCostJsonConverter : JsonConverter<EffectSetDiscountPerAdditionalCost>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EffectSetDiscountPerAdditionalCostJsonConverter" /> class.
        /// </summary>
        public EffectSetDiscountPerAdditionalCostJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EffectSetDiscountPerAdditionalCost" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EffectSetDiscountPerAdditionalCost Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EffectSetDiscountPerAdditionalCost.EffectTypeEnum?> effectType = default;
            Option<SetDiscountPerAdditionalCostEffectProps> props = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "effectType":
                            string effectTypeRawValue = utf8JsonReader.GetString();
                            if (effectTypeRawValue != null)
                            {
                                EffectSetDiscountPerAdditionalCost.EffectTypeEnum? effectTypeValue = EffectSetDiscountPerAdditionalCost.EffectTypeEnumFromStringOrDefault(effectTypeRawValue);
                                if (effectTypeValue == null)
                                    throw new JsonException();
                                effectType = new Option<EffectSetDiscountPerAdditionalCost.EffectTypeEnum?>(effectTypeValue);
                            }
                            break;
                        case "props":
                            props = new Option<SetDiscountPerAdditionalCostEffectProps>(JsonSerializer.Deserialize<SetDiscountPerAdditionalCostEffectProps>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!effectType.IsSet)
                throw new ArgumentException("Property is required for class EffectSetDiscountPerAdditionalCost.", nameof(effectType));

            if (!props.IsSet)
                throw new ArgumentException("Property is required for class EffectSetDiscountPerAdditionalCost.", nameof(props));

            if (effectType.IsSet && effectType.Value == null)
                throw new ArgumentNullException(nameof(effectType), "Property is not nullable for class EffectSetDiscountPerAdditionalCost.");

            if (props.IsSet && props.Value == null)
                throw new ArgumentNullException(nameof(props), "Property is not nullable for class EffectSetDiscountPerAdditionalCost.");

            return new EffectSetDiscountPerAdditionalCost(effectType.Value.Value, props.Value);
        }

        /// <summary>
        /// Serializes a <see cref="EffectSetDiscountPerAdditionalCost" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="effectSetDiscountPerAdditionalCost"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EffectSetDiscountPerAdditionalCost effectSetDiscountPerAdditionalCost, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, effectSetDiscountPerAdditionalCost, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EffectSetDiscountPerAdditionalCost" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="effectSetDiscountPerAdditionalCost"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EffectSetDiscountPerAdditionalCost effectSetDiscountPerAdditionalCost, JsonSerializerOptions jsonSerializerOptions)
        {
            if (effectSetDiscountPerAdditionalCost.Props == null)
                throw new ArgumentNullException(nameof(effectSetDiscountPerAdditionalCost.Props), "Property is required for class EffectSetDiscountPerAdditionalCost.");

            var effectTypeRawValue = EffectSetDiscountPerAdditionalCost.EffectTypeEnumToJsonValue(effectSetDiscountPerAdditionalCost.EffectType);
            writer.WriteString("effectType", effectTypeRawValue);
            writer.WritePropertyName("props");
            JsonSerializer.Serialize(writer, effectSetDiscountPerAdditionalCost.Props, jsonSerializerOptions);
        }
    }
}
