// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// ExperimentVariantResult
    /// </summary>
    public partial class ExperimentVariantResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExperimentVariantResult" /> class.
        /// </summary>
        /// <param name="variantId">The ID of the variant.</param>
        /// <param name="variantName">The name of the variant.</param>
        /// <param name="variantWeight">The weight of the variant.</param>
        /// <param name="isWinner">Calculated flag if the variant is the winner.</param>
        /// <param name="totalRevenue">The total, pre-discount value of all items purchased in a customer session.</param>
        /// <param name="sessionsCount">The number of all closed sessions.</param>
        /// <param name="avgItemsPerSession">The number of items from sessions divided by the number of sessions.</param>
        /// <param name="avgSessionValue">The average customer session value, calculated by dividing the revenue value by the number of sessions.</param>
        /// <param name="avgDiscountedSessionValue">The average customer session value, calculated by dividing the revenue value by the number of sessions.</param>
        /// <param name="totalDiscounts">The total value of discounts given for cart items in sessions.</param>
        /// <param name="couponsCount">The number of times a coupon was successfully redeemed in sessions.</param>
        [JsonConstructor]
        public ExperimentVariantResult(Option<long?> variantId = default, Option<string> variantName = default, Option<long?> variantWeight = default, Option<bool?> isWinner = default, Option<decimal?> totalRevenue = default, Option<decimal?> sessionsCount = default, Option<decimal?> avgItemsPerSession = default, Option<decimal?> avgSessionValue = default, Option<decimal?> avgDiscountedSessionValue = default, Option<decimal?> totalDiscounts = default, Option<decimal?> couponsCount = default)
        {
            VariantIdOption = variantId;
            VariantNameOption = variantName;
            VariantWeightOption = variantWeight;
            IsWinnerOption = isWinner;
            TotalRevenueOption = totalRevenue;
            SessionsCountOption = sessionsCount;
            AvgItemsPerSessionOption = avgItemsPerSession;
            AvgSessionValueOption = avgSessionValue;
            AvgDiscountedSessionValueOption = avgDiscountedSessionValue;
            TotalDiscountsOption = totalDiscounts;
            CouponsCountOption = couponsCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of VariantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> VariantIdOption { get; private set; }

        /// <summary>
        /// The ID of the variant.
        /// </summary>
        /// <value>The ID of the variant.</value>
        /* <example>1</example> */
        [JsonPropertyName("variantId")]
        public long? VariantId { get { return this.VariantIdOption; } set { this.VariantIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of VariantName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> VariantNameOption { get; private set; }

        /// <summary>
        /// The name of the variant.
        /// </summary>
        /// <value>The name of the variant.</value>
        /* <example>Variant A</example> */
        [JsonPropertyName("variantName")]
        public string VariantName { get { return this.VariantNameOption; } set { this.VariantNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of VariantWeight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> VariantWeightOption { get; private set; }

        /// <summary>
        /// The weight of the variant.
        /// </summary>
        /// <value>The weight of the variant.</value>
        /* <example>50</example> */
        [JsonPropertyName("variantWeight")]
        public long? VariantWeight { get { return this.VariantWeightOption; } set { this.VariantWeightOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of IsWinner
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsWinnerOption { get; private set; }

        /// <summary>
        /// Calculated flag if the variant is the winner.
        /// </summary>
        /// <value>Calculated flag if the variant is the winner.</value>
        /* <example>true</example> */
        [JsonPropertyName("isWinner")]
        public bool? IsWinner { get { return this.IsWinnerOption; } set { this.IsWinnerOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of TotalRevenue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TotalRevenueOption { get; private set; }

        /// <summary>
        /// The total, pre-discount value of all items purchased in a customer session.
        /// </summary>
        /// <value>The total, pre-discount value of all items purchased in a customer session.</value>
        /* <example>100</example> */
        [JsonPropertyName("totalRevenue")]
        public decimal? TotalRevenue { get { return this.TotalRevenueOption; } set { this.TotalRevenueOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of SessionsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> SessionsCountOption { get; private set; }

        /// <summary>
        /// The number of all closed sessions.
        /// </summary>
        /// <value>The number of all closed sessions.</value>
        /* <example>100</example> */
        [JsonPropertyName("sessionsCount")]
        public decimal? SessionsCount { get { return this.SessionsCountOption; } set { this.SessionsCountOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of AvgItemsPerSession
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AvgItemsPerSessionOption { get; private set; }

        /// <summary>
        /// The number of items from sessions divided by the number of sessions.
        /// </summary>
        /// <value>The number of items from sessions divided by the number of sessions.</value>
        /* <example>100</example> */
        [JsonPropertyName("avgItemsPerSession")]
        public decimal? AvgItemsPerSession { get { return this.AvgItemsPerSessionOption; } set { this.AvgItemsPerSessionOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of AvgSessionValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AvgSessionValueOption { get; private set; }

        /// <summary>
        /// The average customer session value, calculated by dividing the revenue value by the number of sessions.
        /// </summary>
        /// <value>The average customer session value, calculated by dividing the revenue value by the number of sessions.</value>
        /* <example>100</example> */
        [JsonPropertyName("avgSessionValue")]
        public decimal? AvgSessionValue { get { return this.AvgSessionValueOption; } set { this.AvgSessionValueOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of AvgDiscountedSessionValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AvgDiscountedSessionValueOption { get; private set; }

        /// <summary>
        /// The average customer session value, calculated by dividing the revenue value by the number of sessions.
        /// </summary>
        /// <value>The average customer session value, calculated by dividing the revenue value by the number of sessions.</value>
        /* <example>100</example> */
        [JsonPropertyName("avgDiscountedSessionValue")]
        public decimal? AvgDiscountedSessionValue { get { return this.AvgDiscountedSessionValueOption; } set { this.AvgDiscountedSessionValueOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of TotalDiscounts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TotalDiscountsOption { get; private set; }

        /// <summary>
        /// The total value of discounts given for cart items in sessions.
        /// </summary>
        /// <value>The total value of discounts given for cart items in sessions.</value>
        /* <example>10</example> */
        [JsonPropertyName("totalDiscounts")]
        public decimal? TotalDiscounts { get { return this.TotalDiscountsOption; } set { this.TotalDiscountsOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of CouponsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CouponsCountOption { get; private set; }

        /// <summary>
        /// The number of times a coupon was successfully redeemed in sessions.
        /// </summary>
        /// <value>The number of times a coupon was successfully redeemed in sessions.</value>
        /* <example>12</example> */
        [JsonPropertyName("couponsCount")]
        public decimal? CouponsCount { get { return this.CouponsCountOption; } set { this.CouponsCountOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExperimentVariantResult {\n");
            sb.Append("  VariantId: ").Append(VariantId).Append("\n");
            sb.Append("  VariantName: ").Append(VariantName).Append("\n");
            sb.Append("  VariantWeight: ").Append(VariantWeight).Append("\n");
            sb.Append("  IsWinner: ").Append(IsWinner).Append("\n");
            sb.Append("  TotalRevenue: ").Append(TotalRevenue).Append("\n");
            sb.Append("  SessionsCount: ").Append(SessionsCount).Append("\n");
            sb.Append("  AvgItemsPerSession: ").Append(AvgItemsPerSession).Append("\n");
            sb.Append("  AvgSessionValue: ").Append(AvgSessionValue).Append("\n");
            sb.Append("  AvgDiscountedSessionValue: ").Append(AvgDiscountedSessionValue).Append("\n");
            sb.Append("  TotalDiscounts: ").Append(TotalDiscounts).Append("\n");
            sb.Append("  CouponsCount: ").Append(CouponsCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExperimentVariantResult" />
    /// </summary>
    public class ExperimentVariantResultJsonConverter : JsonConverter<ExperimentVariantResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExperimentVariantResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExperimentVariantResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> variantId = default;
            Option<string> variantName = default;
            Option<long?> variantWeight = default;
            Option<bool?> isWinner = default;
            Option<decimal?> totalRevenue = default;
            Option<decimal?> sessionsCount = default;
            Option<decimal?> avgItemsPerSession = default;
            Option<decimal?> avgSessionValue = default;
            Option<decimal?> avgDiscountedSessionValue = default;
            Option<decimal?> totalDiscounts = default;
            Option<decimal?> couponsCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "variantId":
                            variantId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "variantName":
                            variantName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "variantWeight":
                            variantWeight = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "isWinner":
                            isWinner = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "totalRevenue":
                            totalRevenue = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "sessionsCount":
                            sessionsCount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "avgItemsPerSession":
                            avgItemsPerSession = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "avgSessionValue":
                            avgSessionValue = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "avgDiscountedSessionValue":
                            avgDiscountedSessionValue = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "totalDiscounts":
                            totalDiscounts = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "couponsCount":
                            couponsCount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (variantId.IsSet && variantId.Value == null)
                throw new ArgumentNullException(nameof(variantId), "Property is not nullable for class ExperimentVariantResult.");

            if (variantWeight.IsSet && variantWeight.Value == null)
                throw new ArgumentNullException(nameof(variantWeight), "Property is not nullable for class ExperimentVariantResult.");

            if (isWinner.IsSet && isWinner.Value == null)
                throw new ArgumentNullException(nameof(isWinner), "Property is not nullable for class ExperimentVariantResult.");

            if (totalRevenue.IsSet && totalRevenue.Value == null)
                throw new ArgumentNullException(nameof(totalRevenue), "Property is not nullable for class ExperimentVariantResult.");

            if (sessionsCount.IsSet && sessionsCount.Value == null)
                throw new ArgumentNullException(nameof(sessionsCount), "Property is not nullable for class ExperimentVariantResult.");

            if (avgItemsPerSession.IsSet && avgItemsPerSession.Value == null)
                throw new ArgumentNullException(nameof(avgItemsPerSession), "Property is not nullable for class ExperimentVariantResult.");

            if (avgSessionValue.IsSet && avgSessionValue.Value == null)
                throw new ArgumentNullException(nameof(avgSessionValue), "Property is not nullable for class ExperimentVariantResult.");

            if (avgDiscountedSessionValue.IsSet && avgDiscountedSessionValue.Value == null)
                throw new ArgumentNullException(nameof(avgDiscountedSessionValue), "Property is not nullable for class ExperimentVariantResult.");

            if (totalDiscounts.IsSet && totalDiscounts.Value == null)
                throw new ArgumentNullException(nameof(totalDiscounts), "Property is not nullable for class ExperimentVariantResult.");

            if (couponsCount.IsSet && couponsCount.Value == null)
                throw new ArgumentNullException(nameof(couponsCount), "Property is not nullable for class ExperimentVariantResult.");

            return new ExperimentVariantResult(variantId, variantName, variantWeight, isWinner, totalRevenue, sessionsCount, avgItemsPerSession, avgSessionValue, avgDiscountedSessionValue, totalDiscounts, couponsCount);
        }

        /// <summary>
        /// Serializes a <see cref="ExperimentVariantResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="experimentVariantResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExperimentVariantResult experimentVariantResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, experimentVariantResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExperimentVariantResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="experimentVariantResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExperimentVariantResult experimentVariantResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (experimentVariantResult.VariantNameOption.IsSet && experimentVariantResult.VariantName == null)
                throw new ArgumentNullException(nameof(experimentVariantResult.VariantName), "Property is required for class ExperimentVariantResult.");

            if (experimentVariantResult.VariantIdOption.IsSet)
                writer.WriteNumber("variantId", experimentVariantResult.VariantIdOption.Value.Value);

            if (experimentVariantResult.VariantNameOption.IsSet)
                writer.WriteString("variantName", experimentVariantResult.VariantName);

            if (experimentVariantResult.VariantWeightOption.IsSet)
                writer.WriteNumber("variantWeight", experimentVariantResult.VariantWeightOption.Value.Value);

            if (experimentVariantResult.IsWinnerOption.IsSet)
                writer.WriteBoolean("isWinner", experimentVariantResult.IsWinnerOption.Value.Value);

            if (experimentVariantResult.TotalRevenueOption.IsSet)
                writer.WriteNumber("totalRevenue", experimentVariantResult.TotalRevenueOption.Value.Value);

            if (experimentVariantResult.SessionsCountOption.IsSet)
                writer.WriteNumber("sessionsCount", experimentVariantResult.SessionsCountOption.Value.Value);

            if (experimentVariantResult.AvgItemsPerSessionOption.IsSet)
                writer.WriteNumber("avgItemsPerSession", experimentVariantResult.AvgItemsPerSessionOption.Value.Value);

            if (experimentVariantResult.AvgSessionValueOption.IsSet)
                writer.WriteNumber("avgSessionValue", experimentVariantResult.AvgSessionValueOption.Value.Value);

            if (experimentVariantResult.AvgDiscountedSessionValueOption.IsSet)
                writer.WriteNumber("avgDiscountedSessionValue", experimentVariantResult.AvgDiscountedSessionValueOption.Value.Value);

            if (experimentVariantResult.TotalDiscountsOption.IsSet)
                writer.WriteNumber("totalDiscounts", experimentVariantResult.TotalDiscountsOption.Value.Value);

            if (experimentVariantResult.CouponsCountOption.IsSet)
                writer.WriteNumber("couponsCount", experimentVariantResult.CouponsCountOption.Value.Value);
        }
    }
}
