// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// Details about a campaign that influenced the final price.
    /// </summary>
    public partial class InfluencingCampaignDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InfluencingCampaignDetails" /> class.
        /// </summary>
        /// <param name="campaignId">Identifier of the campaign that influenced the final price.</param>
        /// <param name="discountValue">Discount value applied by the campaign.</param>
        [JsonConstructor]
        public InfluencingCampaignDetails(long campaignId, decimal discountValue)
        {
            CampaignId = campaignId;
            DiscountValue = discountValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Identifier of the campaign that influenced the final price.
        /// </summary>
        /// <value>Identifier of the campaign that influenced the final price.</value>
        [JsonPropertyName("campaignId")]
        public long CampaignId { get; set; }

        /// <summary>
        /// Discount value applied by the campaign.
        /// </summary>
        /// <value>Discount value applied by the campaign.</value>
        [JsonPropertyName("discountValue")]
        public decimal DiscountValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InfluencingCampaignDetails {\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  DiscountValue: ").Append(DiscountValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InfluencingCampaignDetails" />
    /// </summary>
    public class InfluencingCampaignDetailsJsonConverter : JsonConverter<InfluencingCampaignDetails>
    {
        /// <summary>
        /// Deserializes json to <see cref="InfluencingCampaignDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InfluencingCampaignDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> campaignId = default;
            Option<decimal?> discountValue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "campaignId":
                            campaignId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "discountValue":
                            discountValue = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!campaignId.IsSet)
                throw new ArgumentException("Property is required for class InfluencingCampaignDetails.", nameof(campaignId));

            if (!discountValue.IsSet)
                throw new ArgumentException("Property is required for class InfluencingCampaignDetails.", nameof(discountValue));

            if (campaignId.IsSet && campaignId.Value == null)
                throw new ArgumentNullException(nameof(campaignId), "Property is not nullable for class InfluencingCampaignDetails.");

            if (discountValue.IsSet && discountValue.Value == null)
                throw new ArgumentNullException(nameof(discountValue), "Property is not nullable for class InfluencingCampaignDetails.");

            return new InfluencingCampaignDetails(campaignId.Value.Value, discountValue.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="InfluencingCampaignDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="influencingCampaignDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InfluencingCampaignDetails influencingCampaignDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, influencingCampaignDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InfluencingCampaignDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="influencingCampaignDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InfluencingCampaignDetails influencingCampaignDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("campaignId", influencingCampaignDetails.CampaignId);

            writer.WriteNumber("discountValue", influencingCampaignDetails.DiscountValue);
        }
    }
}
