// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// ItemAttribute
    /// </summary>
    public partial class ItemAttribute : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemAttribute" /> class.
        /// </summary>
        /// <param name="attributeid">The ID of the attribute of the item.</param>
        /// <param name="name">The name of the attribute.</param>
        /// <param name="value">value</param>
        [JsonConstructor]
        public ItemAttribute(long attributeid, string name, Object value = default)
        {
            Attributeid = attributeid;
            Name = name;
            Value = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The ID of the attribute of the item.
        /// </summary>
        /// <value>The ID of the attribute of the item.</value>
        /* <example>6</example> */
        [JsonPropertyName("attributeid")]
        public long Attributeid { get; set; }

        /// <summary>
        /// The name of the attribute.
        /// </summary>
        /// <value>The name of the attribute.</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ItemAttribute {\n");
            sb.Append("  Attributeid: ").Append(Attributeid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ItemAttribute" />
    /// </summary>
    public class ItemAttributeJsonConverter : JsonConverter<ItemAttribute>
    {
        /// <summary>
        /// Deserializes json to <see cref="ItemAttribute" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ItemAttribute Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> attributeid = default;
            Option<string> name = default;
            Option<Object> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "attributeid":
                            attributeid = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "value":
                            value = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!attributeid.IsSet)
                throw new ArgumentException("Property is required for class ItemAttribute.", nameof(attributeid));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ItemAttribute.", nameof(name));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class ItemAttribute.", nameof(value));

            if (attributeid.IsSet && attributeid.Value == null)
                throw new ArgumentNullException(nameof(attributeid), "Property is not nullable for class ItemAttribute.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ItemAttribute.");

            return new ItemAttribute(attributeid.Value.Value, name.Value, value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="ItemAttribute" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="itemAttribute"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ItemAttribute itemAttribute, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, itemAttribute, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ItemAttribute" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="itemAttribute"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ItemAttribute itemAttribute, JsonSerializerOptions jsonSerializerOptions)
        {
            if (itemAttribute.Name == null)
                throw new ArgumentNullException(nameof(itemAttribute.Name), "Property is required for class ItemAttribute.");

            writer.WriteNumber("attributeid", itemAttribute.Attributeid);

            writer.WriteString("name", itemAttribute.Name);

            if (itemAttribute.Value != null)
            {
                writer.WritePropertyName("value");
                JsonSerializer.Serialize(writer, itemAttribute.Value, jsonSerializerOptions);
            }
            else
                writer.WriteNull("value");
        }
    }
}
