// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// NewApplicationCIF
    /// </summary>
    public partial class NewApplicationCIF : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewApplicationCIF" /> class.
        /// </summary>
        /// <param name="name">The name of the Application cart item filter used in API requests.</param>
        /// <param name="description">A short description of the Application cart item filter.</param>
        /// <param name="activeExpressionId">The ID of the expression that the Application cart item filter uses.</param>
        /// <param name="modifiedBy">The ID of the user who last updated the Application cart item filter.</param>
        /// <param name="createdBy">The ID of the user who created the Application cart item filter.</param>
        /// <param name="modified">Timestamp of the most recent update to the Application cart item filter.</param>
        [JsonConstructor]
        public NewApplicationCIF(string name, Option<string> description = default, Option<long?> activeExpressionId = default, Option<long?> modifiedBy = default, Option<long?> createdBy = default, Option<DateTime?> modified = default)
        {
            Name = name;
            DescriptionOption = description;
            ActiveExpressionIdOption = activeExpressionId;
            ModifiedByOption = modifiedBy;
            CreatedByOption = createdBy;
            ModifiedOption = modified;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The name of the Application cart item filter used in API requests.
        /// </summary>
        /// <value>The name of the Application cart item filter used in API requests.</value>
        /* <example>Filter items by product</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DescriptionOption { get; private set; }

        /// <summary>
        /// A short description of the Application cart item filter.
        /// </summary>
        /// <value>A short description of the Application cart item filter.</value>
        /* <example>This filter allows filtering by shoes</example> */
        [JsonPropertyName("description")]
        public string Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of ActiveExpressionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ActiveExpressionIdOption { get; private set; }

        /// <summary>
        /// The ID of the expression that the Application cart item filter uses.
        /// </summary>
        /// <value>The ID of the expression that the Application cart item filter uses.</value>
        /* <example>1</example> */
        [JsonPropertyName("activeExpressionId")]
        public long? ActiveExpressionId { get { return this.ActiveExpressionIdOption; } set { this.ActiveExpressionIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ModifiedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ModifiedByOption { get; private set; }

        /// <summary>
        /// The ID of the user who last updated the Application cart item filter.
        /// </summary>
        /// <value>The ID of the user who last updated the Application cart item filter.</value>
        /* <example>334</example> */
        [JsonPropertyName("modifiedBy")]
        public long? ModifiedBy { get { return this.ModifiedByOption; } set { this.ModifiedByOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CreatedByOption { get; private set; }

        /// <summary>
        /// The ID of the user who created the Application cart item filter.
        /// </summary>
        /// <value>The ID of the user who created the Application cart item filter.</value>
        /* <example>216</example> */
        [JsonPropertyName("createdBy")]
        public long? CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Modified
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ModifiedOption { get; private set; }

        /// <summary>
        /// Timestamp of the most recent update to the Application cart item filter.
        /// </summary>
        /// <value>Timestamp of the most recent update to the Application cart item filter.</value>
        [JsonPropertyName("modified")]
        public DateTime? Modified { get { return this.ModifiedOption; } set { this.ModifiedOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NewApplicationCIF {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ActiveExpressionId: ").Append(ActiveExpressionId).Append("\n");
            sb.Append("  ModifiedBy: ").Append(ModifiedBy).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewApplicationCIF" />
    /// </summary>
    public class NewApplicationCIFJsonConverter : JsonConverter<NewApplicationCIF>
    {
        /// <summary>
        /// The format to use to serialize Modified
        /// </summary>
        public static string ModifiedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NewApplicationCIF" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NewApplicationCIF Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> description = default;
            Option<long?> activeExpressionId = default;
            Option<long?> modifiedBy = default;
            Option<long?> createdBy = default;
            Option<DateTime?> modified = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "activeExpressionId":
                            activeExpressionId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "modifiedBy":
                            modifiedBy = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "createdBy":
                            createdBy = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "modified":
                            modified = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class NewApplicationCIF.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class NewApplicationCIF.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class NewApplicationCIF.");

            if (activeExpressionId.IsSet && activeExpressionId.Value == null)
                throw new ArgumentNullException(nameof(activeExpressionId), "Property is not nullable for class NewApplicationCIF.");

            if (modifiedBy.IsSet && modifiedBy.Value == null)
                throw new ArgumentNullException(nameof(modifiedBy), "Property is not nullable for class NewApplicationCIF.");

            if (createdBy.IsSet && createdBy.Value == null)
                throw new ArgumentNullException(nameof(createdBy), "Property is not nullable for class NewApplicationCIF.");

            if (modified.IsSet && modified.Value == null)
                throw new ArgumentNullException(nameof(modified), "Property is not nullable for class NewApplicationCIF.");

            return new NewApplicationCIF(name.Value, description, activeExpressionId, modifiedBy, createdBy, modified);
        }

        /// <summary>
        /// Serializes a <see cref="NewApplicationCIF" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newApplicationCIF"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NewApplicationCIF newApplicationCIF, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, newApplicationCIF, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NewApplicationCIF" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newApplicationCIF"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NewApplicationCIF newApplicationCIF, JsonSerializerOptions jsonSerializerOptions)
        {
            if (newApplicationCIF.Name == null)
                throw new ArgumentNullException(nameof(newApplicationCIF.Name), "Property is required for class NewApplicationCIF.");

            if (newApplicationCIF.DescriptionOption.IsSet && newApplicationCIF.Description == null)
                throw new ArgumentNullException(nameof(newApplicationCIF.Description), "Property is required for class NewApplicationCIF.");

            writer.WriteString("name", newApplicationCIF.Name);

            if (newApplicationCIF.DescriptionOption.IsSet)
                writer.WriteString("description", newApplicationCIF.Description);

            if (newApplicationCIF.ActiveExpressionIdOption.IsSet)
                writer.WriteNumber("activeExpressionId", newApplicationCIF.ActiveExpressionIdOption.Value.Value);

            if (newApplicationCIF.ModifiedByOption.IsSet)
                writer.WriteNumber("modifiedBy", newApplicationCIF.ModifiedByOption.Value.Value);

            if (newApplicationCIF.CreatedByOption.IsSet)
                writer.WriteNumber("createdBy", newApplicationCIF.CreatedByOption.Value.Value);

            if (newApplicationCIF.ModifiedOption.IsSet)
                writer.WriteString("modified", newApplicationCIF.ModifiedOption.Value.Value.ToString(ModifiedFormat));
        }
    }
}
