// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// NewReturn
    /// </summary>
    public partial class NewReturn : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewReturn" /> class.
        /// </summary>
        /// <param name="returnedCartItems">List of cart items to be returned.</param>
        [JsonConstructor]
        public NewReturn(List<ReturnedCartItem> returnedCartItems)
        {
            ReturnedCartItems = returnedCartItems;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of cart items to be returned.
        /// </summary>
        /// <value>List of cart items to be returned.</value>
        [JsonPropertyName("returnedCartItems")]
        public List<ReturnedCartItem> ReturnedCartItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NewReturn {\n");
            sb.Append("  ReturnedCartItems: ").Append(ReturnedCartItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewReturn" />
    /// </summary>
    public class NewReturnJsonConverter : JsonConverter<NewReturn>
    {
        /// <summary>
        /// Deserializes json to <see cref="NewReturn" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NewReturn Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ReturnedCartItem>> returnedCartItems = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "returnedCartItems":
                            returnedCartItems = new Option<List<ReturnedCartItem>>(JsonSerializer.Deserialize<List<ReturnedCartItem>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!returnedCartItems.IsSet)
                throw new ArgumentException("Property is required for class NewReturn.", nameof(returnedCartItems));

            if (returnedCartItems.IsSet && returnedCartItems.Value == null)
                throw new ArgumentNullException(nameof(returnedCartItems), "Property is not nullable for class NewReturn.");

            return new NewReturn(returnedCartItems.Value);
        }

        /// <summary>
        /// Serializes a <see cref="NewReturn" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newReturn"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NewReturn newReturn, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, newReturn, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NewReturn" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newReturn"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NewReturn newReturn, JsonSerializerOptions jsonSerializerOptions)
        {
            if (newReturn.ReturnedCartItems == null)
                throw new ArgumentNullException(nameof(newReturn.ReturnedCartItems), "Property is required for class NewReturn.");

            writer.WritePropertyName("returnedCartItems");
            JsonSerializer.Serialize(writer, newReturn.ReturnedCartItems, jsonSerializerOptions);
        }
    }
}
