// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// Holds a reference to the campaign, the referral and the reason for which that referral was rejected. Should only be present when there is a &#39;rejectReferral&#39; effect.
    /// </summary>
    public partial class ReferralRejectionReason : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReferralRejectionReason" /> class.
        /// </summary>
        /// <param name="campaignId">campaignId</param>
        /// <param name="referralId">referralId</param>
        /// <param name="reason">reason</param>
        [JsonConstructor]
        public ReferralRejectionReason(long campaignId, long referralId, ReasonEnum reason)
        {
            CampaignId = campaignId;
            ReferralId = referralId;
            Reason = reason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Reason
        /// </summary>
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum ReferralNotFound for value: ReferralNotFound
            /// </summary>
            ReferralNotFound = 1,

            /// <summary>
            /// Enum ReferralRecipientIdSameAsAdvocate for value: ReferralRecipientIdSameAsAdvocate
            /// </summary>
            ReferralRecipientIdSameAsAdvocate = 2,

            /// <summary>
            /// Enum ReferralPartOfNotRunningCampaign for value: ReferralPartOfNotRunningCampaign
            /// </summary>
            ReferralPartOfNotRunningCampaign = 3,

            /// <summary>
            /// Enum ReferralLimitReached for value: ReferralLimitReached
            /// </summary>
            ReferralLimitReached = 4,

            /// <summary>
            /// Enum CampaignLimitReached for value: CampaignLimitReached
            /// </summary>
            CampaignLimitReached = 5,

            /// <summary>
            /// Enum ProfileLimitReached for value: ProfileLimitReached
            /// </summary>
            ProfileLimitReached = 6,

            /// <summary>
            /// Enum ReferralRecipientDoesNotMatch for value: ReferralRecipientDoesNotMatch
            /// </summary>
            ReferralRecipientDoesNotMatch = 7,

            /// <summary>
            /// Enum ReferralExpired for value: ReferralExpired
            /// </summary>
            ReferralExpired = 8,

            /// <summary>
            /// Enum ReferralStartDateInFuture for value: ReferralStartDateInFuture
            /// </summary>
            ReferralStartDateInFuture = 9,

            /// <summary>
            /// Enum ReferralRejectedByCondition for value: ReferralRejectedByCondition
            /// </summary>
            ReferralRejectedByCondition = 10,

            /// <summary>
            /// Enum EffectCouldNotBeApplied for value: EffectCouldNotBeApplied
            /// </summary>
            EffectCouldNotBeApplied = 11,

            /// <summary>
            /// Enum ReferralPartOfNotTriggeredCampaign for value: ReferralPartOfNotTriggeredCampaign
            /// </summary>
            ReferralPartOfNotTriggeredCampaign = 12
        }

        /// <summary>
        /// Returns a <see cref="ReasonEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ReasonEnum ReasonEnumFromString(string value)
        {
            if (value.Equals("ReferralNotFound"))
                return ReasonEnum.ReferralNotFound;

            if (value.Equals("ReferralRecipientIdSameAsAdvocate"))
                return ReasonEnum.ReferralRecipientIdSameAsAdvocate;

            if (value.Equals("ReferralPartOfNotRunningCampaign"))
                return ReasonEnum.ReferralPartOfNotRunningCampaign;

            if (value.Equals("ReferralLimitReached"))
                return ReasonEnum.ReferralLimitReached;

            if (value.Equals("CampaignLimitReached"))
                return ReasonEnum.CampaignLimitReached;

            if (value.Equals("ProfileLimitReached"))
                return ReasonEnum.ProfileLimitReached;

            if (value.Equals("ReferralRecipientDoesNotMatch"))
                return ReasonEnum.ReferralRecipientDoesNotMatch;

            if (value.Equals("ReferralExpired"))
                return ReasonEnum.ReferralExpired;

            if (value.Equals("ReferralStartDateInFuture"))
                return ReasonEnum.ReferralStartDateInFuture;

            if (value.Equals("ReferralRejectedByCondition"))
                return ReasonEnum.ReferralRejectedByCondition;

            if (value.Equals("EffectCouldNotBeApplied"))
                return ReasonEnum.EffectCouldNotBeApplied;

            if (value.Equals("ReferralPartOfNotTriggeredCampaign"))
                return ReasonEnum.ReferralPartOfNotTriggeredCampaign;

            throw new NotImplementedException($"Could not convert value to type ReasonEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ReasonEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ReasonEnum? ReasonEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ReferralNotFound"))
                return ReasonEnum.ReferralNotFound;

            if (value.Equals("ReferralRecipientIdSameAsAdvocate"))
                return ReasonEnum.ReferralRecipientIdSameAsAdvocate;

            if (value.Equals("ReferralPartOfNotRunningCampaign"))
                return ReasonEnum.ReferralPartOfNotRunningCampaign;

            if (value.Equals("ReferralLimitReached"))
                return ReasonEnum.ReferralLimitReached;

            if (value.Equals("CampaignLimitReached"))
                return ReasonEnum.CampaignLimitReached;

            if (value.Equals("ProfileLimitReached"))
                return ReasonEnum.ProfileLimitReached;

            if (value.Equals("ReferralRecipientDoesNotMatch"))
                return ReasonEnum.ReferralRecipientDoesNotMatch;

            if (value.Equals("ReferralExpired"))
                return ReasonEnum.ReferralExpired;

            if (value.Equals("ReferralStartDateInFuture"))
                return ReasonEnum.ReferralStartDateInFuture;

            if (value.Equals("ReferralRejectedByCondition"))
                return ReasonEnum.ReferralRejectedByCondition;

            if (value.Equals("EffectCouldNotBeApplied"))
                return ReasonEnum.EffectCouldNotBeApplied;

            if (value.Equals("ReferralPartOfNotTriggeredCampaign"))
                return ReasonEnum.ReferralPartOfNotTriggeredCampaign;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ReasonEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ReasonEnumToJsonValue(ReasonEnum value)
        {
            if (value == ReasonEnum.ReferralNotFound)
                return "ReferralNotFound";

            if (value == ReasonEnum.ReferralRecipientIdSameAsAdvocate)
                return "ReferralRecipientIdSameAsAdvocate";

            if (value == ReasonEnum.ReferralPartOfNotRunningCampaign)
                return "ReferralPartOfNotRunningCampaign";

            if (value == ReasonEnum.ReferralLimitReached)
                return "ReferralLimitReached";

            if (value == ReasonEnum.CampaignLimitReached)
                return "CampaignLimitReached";

            if (value == ReasonEnum.ProfileLimitReached)
                return "ProfileLimitReached";

            if (value == ReasonEnum.ReferralRecipientDoesNotMatch)
                return "ReferralRecipientDoesNotMatch";

            if (value == ReasonEnum.ReferralExpired)
                return "ReferralExpired";

            if (value == ReasonEnum.ReferralStartDateInFuture)
                return "ReferralStartDateInFuture";

            if (value == ReasonEnum.ReferralRejectedByCondition)
                return "ReferralRejectedByCondition";

            if (value == ReasonEnum.EffectCouldNotBeApplied)
                return "EffectCouldNotBeApplied";

            if (value == ReasonEnum.ReferralPartOfNotTriggeredCampaign)
                return "ReferralPartOfNotTriggeredCampaign";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        /* <example>ReferralNotFound</example> */
        [JsonPropertyName("reason")]
        public ReasonEnum Reason { get; set; }

        /// <summary>
        /// Gets or Sets CampaignId
        /// </summary>
        [JsonPropertyName("campaignId")]
        public long CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets ReferralId
        /// </summary>
        [JsonPropertyName("referralId")]
        public long ReferralId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReferralRejectionReason {\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  ReferralId: ").Append(ReferralId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ReferralRejectionReason" />
    /// </summary>
    public class ReferralRejectionReasonJsonConverter : JsonConverter<ReferralRejectionReason>
    {
        /// <summary>
        /// Deserializes json to <see cref="ReferralRejectionReason" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ReferralRejectionReason Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> campaignId = default;
            Option<long?> referralId = default;
            Option<ReferralRejectionReason.ReasonEnum?> reason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "campaignId":
                            campaignId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "referralId":
                            referralId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "reason":
                            string reasonRawValue = utf8JsonReader.GetString();
                            if (reasonRawValue != null)
                                reason = new Option<ReferralRejectionReason.ReasonEnum?>(ReferralRejectionReason.ReasonEnumFromStringOrDefault(reasonRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!campaignId.IsSet)
                throw new ArgumentException("Property is required for class ReferralRejectionReason.", nameof(campaignId));

            if (!referralId.IsSet)
                throw new ArgumentException("Property is required for class ReferralRejectionReason.", nameof(referralId));

            if (!reason.IsSet)
                throw new ArgumentException("Property is required for class ReferralRejectionReason.", nameof(reason));

            if (campaignId.IsSet && campaignId.Value == null)
                throw new ArgumentNullException(nameof(campaignId), "Property is not nullable for class ReferralRejectionReason.");

            if (referralId.IsSet && referralId.Value == null)
                throw new ArgumentNullException(nameof(referralId), "Property is not nullable for class ReferralRejectionReason.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class ReferralRejectionReason.");

            return new ReferralRejectionReason(campaignId.Value.Value, referralId.Value.Value, reason.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="ReferralRejectionReason" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="referralRejectionReason"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ReferralRejectionReason referralRejectionReason, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, referralRejectionReason, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ReferralRejectionReason" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="referralRejectionReason"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ReferralRejectionReason referralRejectionReason, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("campaignId", referralRejectionReason.CampaignId);

            writer.WriteNumber("referralId", referralRejectionReason.ReferralId);

            var reasonRawValue = ReferralRejectionReason.ReasonEnumToJsonValue(referralRejectionReason.Reason);
            writer.WriteString("reason", reasonRawValue);
        }
    }
}
