// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// You can use notifications to inform customers of certain events. There are four types of notification messages:  - &#x60;Info&#x60; - &#x60;Offer&#x60; - &#x60;Error&#x60; - &#x60;Misc&#x60;  It is up to you to use the Rule Builder to decide why and when to show notifications. Notifications can be used as both rule effects and failure effects.  A common use case is to display the notification at the top of the cart view in your web app. You can use the notification type to vary the styling of the notification message.
    /// </summary>
    public partial class ShowNotificationEffectProps : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShowNotificationEffectProps" /> class.
        /// </summary>
        /// <param name="notificationType">The type of notification.</param>
        /// <param name="title">The title of the notification.</param>
        /// <param name="body">The body of the notification.</param>
        [JsonConstructor]
        public ShowNotificationEffectProps(string notificationType, string title, string body)
        {
            NotificationType = notificationType;
            Title = title;
            Body = body;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of notification.
        /// </summary>
        /// <value>The type of notification.</value>
        [JsonPropertyName("notificationType")]
        public string NotificationType { get; set; }

        /// <summary>
        /// The title of the notification.
        /// </summary>
        /// <value>The title of the notification.</value>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// The body of the notification.
        /// </summary>
        /// <value>The body of the notification.</value>
        [JsonPropertyName("body")]
        public string Body { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShowNotificationEffectProps {\n");
            sb.Append("  NotificationType: ").Append(NotificationType).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ShowNotificationEffectProps" />
    /// </summary>
    public partial class ShowNotificationEffectPropsJsonConverter : JsonConverter<ShowNotificationEffectProps>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ShowNotificationEffectPropsJsonConverter" /> class.
        /// </summary>
        public ShowNotificationEffectPropsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ShowNotificationEffectProps" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ShowNotificationEffectProps Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> notificationType = default;
            Option<string> title = default;
            Option<string> body = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "notificationType":
                            notificationType = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "title":
                            title = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "body":
                            body = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!notificationType.IsSet)
                throw new ArgumentException("Property is required for class ShowNotificationEffectProps.", nameof(notificationType));

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class ShowNotificationEffectProps.", nameof(title));

            if (!body.IsSet)
                throw new ArgumentException("Property is required for class ShowNotificationEffectProps.", nameof(body));

            if (notificationType.IsSet && notificationType.Value == null)
                throw new ArgumentNullException(nameof(notificationType), "Property is not nullable for class ShowNotificationEffectProps.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class ShowNotificationEffectProps.");

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class ShowNotificationEffectProps.");

            return new ShowNotificationEffectProps(notificationType.Value, title.Value, body.Value);
        }

        /// <summary>
        /// Serializes a <see cref="ShowNotificationEffectProps" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="showNotificationEffectProps"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ShowNotificationEffectProps showNotificationEffectProps, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, showNotificationEffectProps, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ShowNotificationEffectProps" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="showNotificationEffectProps"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ShowNotificationEffectProps showNotificationEffectProps, JsonSerializerOptions jsonSerializerOptions)
        {
            if (showNotificationEffectProps.NotificationType == null)
                throw new ArgumentNullException(nameof(showNotificationEffectProps.NotificationType), "Property is required for class ShowNotificationEffectProps.");

            if (showNotificationEffectProps.Title == null)
                throw new ArgumentNullException(nameof(showNotificationEffectProps.Title), "Property is required for class ShowNotificationEffectProps.");

            if (showNotificationEffectProps.Body == null)
                throw new ArgumentNullException(nameof(showNotificationEffectProps.Body), "Property is required for class ShowNotificationEffectProps.");

            writer.WriteString("notificationType", showNotificationEffectProps.NotificationType);

            writer.WriteString("title", showNotificationEffectProps.Title);

            writer.WriteString("body", showNotificationEffectProps.Body);
        }
    }
}
