// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// StrikethroughCheckAttributeBlock
    /// </summary>
    public partial class StrikethroughCheckAttributeBlock : CheckAttributeBlock, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StrikethroughCheckAttributeBlock" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for this block.</param>
        /// <param name="type">Identifies the block variant and determines which additional properties are present in it.</param>
        /// <param name="attribute">The attribute path identifier (e.g. \&quot;$Session.Total\&quot;).</param>
        /// <param name="tags">Semantic labels attached to this block.</param>
        /// <param name="value">value</param>
        /// <param name="min">min</param>
        /// <param name="max">max</param>
        /// <param name="values">values</param>
        /// <param name="count">count</param>
        /// <param name="onFailure">Strikethrough blocks evaluated when this block fails or returns false.</param>
        [JsonConstructor]
        public StrikethroughCheckAttributeBlock(string id, string type, string attribute, Option<List<string>> tags = default, Option<Object> value = default, Option<Object> min = default, Option<Object> max = default, Option<Object> values = default, Option<Object> count = default, Option<List<Object>> onFailure = default) : base(id, type, attribute, tags, value, min, max, values, count)
        {
            OnFailureOption = onFailure;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OnFailure
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>> OnFailureOption { get; private set; }

        /// <summary>
        /// Strikethrough blocks evaluated when this block fails or returns false.
        /// </summary>
        /// <value>Strikethrough blocks evaluated when this block fails or returns false.</value>
        [JsonPropertyName("onFailure")]
        public List<Object> OnFailure { get { return this.OnFailureOption.Value; } set { this.OnFailureOption = new Option<List<Object>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StrikethroughCheckAttributeBlock {\n");
            sb.Append("  ").Append(base.ToString()?.Replace("\n", "\n  ")).Append("\n");
            sb.Append("  OnFailure: ").Append(OnFailure).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StrikethroughCheckAttributeBlock" />
    /// </summary>
    public class StrikethroughCheckAttributeBlockJsonConverter : JsonConverter<StrikethroughCheckAttributeBlock>
    {
        /// <summary>
        /// Deserializes json to <see cref="StrikethroughCheckAttributeBlock" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StrikethroughCheckAttributeBlock Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> id = default;
            Option<string> type = default;
            Option<StrikethroughCheckAttributeBlock.OperatorEnum?> varOperator = default;
            Option<string> attribute = default;
            Option<List<string>> tags = default;
            Option<Object> value = default;
            Option<Object> min = default;
            Option<Object> max = default;
            Option<Object> values = default;
            Option<Object> count = default;
            Option<List<Object>> onFailure = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "type":
                            type = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "operator":
                            string varOperatorRawValue = utf8JsonReader.GetString();
                            if (varOperatorRawValue != null)
                                varOperator = new Option<StrikethroughCheckAttributeBlock.OperatorEnum?>(StrikethroughCheckAttributeBlock.OperatorEnumFromStringOrDefault(varOperatorRawValue));
                            break;
                        case "attribute":
                            attribute = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "tags":
                            tags = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "value":
                            value = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "min":
                            min = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "max":
                            max = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "values":
                            values = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "count":
                            count = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "onFailure":
                            onFailure = new Option<List<Object>>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class StrikethroughCheckAttributeBlock.", nameof(id));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class StrikethroughCheckAttributeBlock.", nameof(type));

            if (!varOperator.IsSet)
                throw new ArgumentException("Property is required for class StrikethroughCheckAttributeBlock.", nameof(varOperator));

            if (!attribute.IsSet)
                throw new ArgumentException("Property is required for class StrikethroughCheckAttributeBlock.", nameof(attribute));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class StrikethroughCheckAttributeBlock.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class StrikethroughCheckAttributeBlock.");

            if (varOperator.IsSet && varOperator.Value == null)
                throw new ArgumentNullException(nameof(varOperator), "Property is not nullable for class StrikethroughCheckAttributeBlock.");

            if (attribute.IsSet && attribute.Value == null)
                throw new ArgumentNullException(nameof(attribute), "Property is not nullable for class StrikethroughCheckAttributeBlock.");

            return new StrikethroughCheckAttributeBlock(id.Value, type.Value, attribute.Value, tags, value, min, max, values, count, onFailure);
        }

        /// <summary>
        /// Serializes a <see cref="StrikethroughCheckAttributeBlock" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="strikethroughCheckAttributeBlock"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StrikethroughCheckAttributeBlock strikethroughCheckAttributeBlock, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, strikethroughCheckAttributeBlock, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StrikethroughCheckAttributeBlock" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="strikethroughCheckAttributeBlock"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StrikethroughCheckAttributeBlock strikethroughCheckAttributeBlock, JsonSerializerOptions jsonSerializerOptions)
        {
            if (strikethroughCheckAttributeBlock.Id == null)
                throw new ArgumentNullException(nameof(strikethroughCheckAttributeBlock.Id), "Property is required for class StrikethroughCheckAttributeBlock.");

            if (strikethroughCheckAttributeBlock.Type == null)
                throw new ArgumentNullException(nameof(strikethroughCheckAttributeBlock.Type), "Property is required for class StrikethroughCheckAttributeBlock.");

            if (strikethroughCheckAttributeBlock.Attribute == null)
                throw new ArgumentNullException(nameof(strikethroughCheckAttributeBlock.Attribute), "Property is required for class StrikethroughCheckAttributeBlock.");

            writer.WriteString("id", strikethroughCheckAttributeBlock.Id);

            writer.WriteString("type", strikethroughCheckAttributeBlock.Type);

            writer.WriteString("operator", StrikethroughCheckAttributeBlock.OperatorEnumToJsonValue(strikethroughCheckAttributeBlock.Operator));

            writer.WriteString("attribute", strikethroughCheckAttributeBlock.Attribute);

            if (strikethroughCheckAttributeBlock.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.Tags, jsonSerializerOptions);
            }
            if (strikethroughCheckAttributeBlock.ValueOption.IsSet)
                if (strikethroughCheckAttributeBlock.ValueOption.Value != null)
                {
                    writer.WritePropertyName("value");
                    JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.Value, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("value");
            if (strikethroughCheckAttributeBlock.MinOption.IsSet)
                if (strikethroughCheckAttributeBlock.MinOption.Value != null)
                {
                    writer.WritePropertyName("min");
                    JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.Min, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("min");
            if (strikethroughCheckAttributeBlock.MaxOption.IsSet)
                if (strikethroughCheckAttributeBlock.MaxOption.Value != null)
                {
                    writer.WritePropertyName("max");
                    JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.Max, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("max");
            if (strikethroughCheckAttributeBlock.ValuesOption.IsSet)
                if (strikethroughCheckAttributeBlock.ValuesOption.Value != null)
                {
                    writer.WritePropertyName("values");
                    JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.Values, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("values");
            if (strikethroughCheckAttributeBlock.CountOption.IsSet)
                if (strikethroughCheckAttributeBlock.CountOption.Value != null)
                {
                    writer.WritePropertyName("count");
                    JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.Count, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("count");
            if (strikethroughCheckAttributeBlock.OnFailureOption.IsSet)
            {
                writer.WritePropertyName("onFailure");
                JsonSerializer.Serialize(writer, strikethroughCheckAttributeBlock.OnFailure, jsonSerializerOptions);
            }
        }
    }
}
