// <auto-generated>
/*
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using TalonOneSdk.Client;

namespace TalonOneSdk.Model
{
    /// <summary>
    /// TierWillDowngradeData
    /// </summary>
    public partial class TierWillDowngradeData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TierWillDowngradeData" /> class.
        /// </summary>
        /// <param name="customerProfileID">The integration ID of the customer profile whose tier was downgraded.</param>
        /// <param name="loyaltyProgramID">The ID of the loyalty program.</param>
        /// <param name="currentTier">The name of the customer&#39;s current tier.</param>
        /// <param name="currentPoints">The number of points the customer will have after the tier downgrade.</param>
        /// <param name="pointsRequiredToRemain">The number of points needed for a customer to remain on the same tier.</param>
        /// <param name="subledgerID">The ID of the subledger, when applicable. If this field is empty, the main ledger is used. (default to &quot;&quot;)</param>
        /// <param name="nextTier">The name of the customer&#39;s next tier.</param>
        /// <param name="tierExpirationDate">The date and time the tier expires.</param>
        [JsonConstructor]
        public TierWillDowngradeData(string customerProfileID, long loyaltyProgramID, string currentTier, decimal currentPoints, decimal pointsRequiredToRemain, string subledgerID = @"", Option<string> nextTier = default, Option<DateTime?> tierExpirationDate = default)
        {
            CustomerProfileID = customerProfileID;
            LoyaltyProgramID = loyaltyProgramID;
            CurrentTier = currentTier;
            CurrentPoints = currentPoints;
            PointsRequiredToRemain = pointsRequiredToRemain;
            SubledgerID = subledgerID;
            NextTierOption = nextTier;
            TierExpirationDateOption = tierExpirationDate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The integration ID of the customer profile whose tier was downgraded.
        /// </summary>
        /// <value>The integration ID of the customer profile whose tier was downgraded.</value>
        /* <example>URNGV8294NV</example> */
        [JsonPropertyName("CustomerProfileID")]
        public string CustomerProfileID { get; set; }

        /// <summary>
        /// The ID of the loyalty program.
        /// </summary>
        /// <value>The ID of the loyalty program.</value>
        /* <example>5</example> */
        [JsonPropertyName("LoyaltyProgramID")]
        public long LoyaltyProgramID { get; set; }

        /// <summary>
        /// The name of the customer&#39;s current tier.
        /// </summary>
        /// <value>The name of the customer&#39;s current tier.</value>
        /* <example>Silver</example> */
        [JsonPropertyName("CurrentTier")]
        public string CurrentTier { get; set; }

        /// <summary>
        /// The number of points the customer will have after the tier downgrade.
        /// </summary>
        /// <value>The number of points the customer will have after the tier downgrade.</value>
        /* <example>120.55</example> */
        [JsonPropertyName("CurrentPoints")]
        public decimal CurrentPoints { get; set; }

        /// <summary>
        /// The number of points needed for a customer to remain on the same tier.
        /// </summary>
        /// <value>The number of points needed for a customer to remain on the same tier.</value>
        /* <example>23.51</example> */
        [JsonPropertyName("PointsRequiredToRemain")]
        public decimal PointsRequiredToRemain { get; set; }

        /// <summary>
        /// The ID of the subledger, when applicable. If this field is empty, the main ledger is used.
        /// </summary>
        /// <value>The ID of the subledger, when applicable. If this field is empty, the main ledger is used.</value>
        /* <example>SL001</example> */
        [JsonPropertyName("SubledgerID")]
        public string SubledgerID { get; set; }

        /// <summary>
        /// Used to track the state of NextTier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NextTierOption { get; private set; }

        /// <summary>
        /// The name of the customer&#39;s next tier.
        /// </summary>
        /// <value>The name of the customer&#39;s next tier.</value>
        /* <example>Bronze</example> */
        [JsonPropertyName("NextTier")]
        public string NextTier { get { return this.NextTierOption; } set { this.NextTierOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of TierExpirationDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> TierExpirationDateOption { get; private set; }

        /// <summary>
        /// The date and time the tier expires.
        /// </summary>
        /// <value>The date and time the tier expires.</value>
        /* <example>2023-12-01T12:23:00+02:00</example> */
        [JsonPropertyName("TierExpirationDate")]
        public DateTime? TierExpirationDate { get { return this.TierExpirationDateOption; } set { this.TierExpirationDateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TierWillDowngradeData {\n");
            sb.Append("  CustomerProfileID: ").Append(CustomerProfileID).Append("\n");
            sb.Append("  LoyaltyProgramID: ").Append(LoyaltyProgramID).Append("\n");
            sb.Append("  CurrentTier: ").Append(CurrentTier).Append("\n");
            sb.Append("  CurrentPoints: ").Append(CurrentPoints).Append("\n");
            sb.Append("  PointsRequiredToRemain: ").Append(PointsRequiredToRemain).Append("\n");
            sb.Append("  SubledgerID: ").Append(SubledgerID).Append("\n");
            sb.Append("  NextTier: ").Append(NextTier).Append("\n");
            sb.Append("  TierExpirationDate: ").Append(TierExpirationDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LoyaltyProgramID (long) minimum
            if (this.LoyaltyProgramID < (long)1)
            {
                yield return new ValidationResult("Invalid value for LoyaltyProgramID, must be a value greater than or equal to 1.", new [] { "LoyaltyProgramID" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TierWillDowngradeData" />
    /// </summary>
    public class TierWillDowngradeDataJsonConverter : JsonConverter<TierWillDowngradeData>
    {
        /// <summary>
        /// The format to use to serialize TierExpirationDate
        /// </summary>
        public static string TierExpirationDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TierWillDowngradeData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TierWillDowngradeData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> customerProfileID = default;
            Option<long?> loyaltyProgramID = default;
            Option<string> currentTier = default;
            Option<decimal?> currentPoints = default;
            Option<decimal?> pointsRequiredToRemain = default;
            Option<string> subledgerID = default;
            Option<string> nextTier = default;
            Option<DateTime?> tierExpirationDate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "CustomerProfileID":
                            customerProfileID = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "LoyaltyProgramID":
                            loyaltyProgramID = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "CurrentTier":
                            currentTier = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "CurrentPoints":
                            currentPoints = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "PointsRequiredToRemain":
                            pointsRequiredToRemain = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "SubledgerID":
                            subledgerID = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "NextTier":
                            nextTier = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "TierExpirationDate":
                            tierExpirationDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!customerProfileID.IsSet)
                throw new ArgumentException("Property is required for class TierWillDowngradeData.", nameof(customerProfileID));

            if (!loyaltyProgramID.IsSet)
                throw new ArgumentException("Property is required for class TierWillDowngradeData.", nameof(loyaltyProgramID));

            if (!currentTier.IsSet)
                throw new ArgumentException("Property is required for class TierWillDowngradeData.", nameof(currentTier));

            if (!currentPoints.IsSet)
                throw new ArgumentException("Property is required for class TierWillDowngradeData.", nameof(currentPoints));

            if (!pointsRequiredToRemain.IsSet)
                throw new ArgumentException("Property is required for class TierWillDowngradeData.", nameof(pointsRequiredToRemain));

            if (!subledgerID.IsSet)
                throw new ArgumentException("Property is required for class TierWillDowngradeData.", nameof(subledgerID));

            if (customerProfileID.IsSet && customerProfileID.Value == null)
                throw new ArgumentNullException(nameof(customerProfileID), "Property is not nullable for class TierWillDowngradeData.");

            if (loyaltyProgramID.IsSet && loyaltyProgramID.Value == null)
                throw new ArgumentNullException(nameof(loyaltyProgramID), "Property is not nullable for class TierWillDowngradeData.");

            if (currentTier.IsSet && currentTier.Value == null)
                throw new ArgumentNullException(nameof(currentTier), "Property is not nullable for class TierWillDowngradeData.");

            if (currentPoints.IsSet && currentPoints.Value == null)
                throw new ArgumentNullException(nameof(currentPoints), "Property is not nullable for class TierWillDowngradeData.");

            if (pointsRequiredToRemain.IsSet && pointsRequiredToRemain.Value == null)
                throw new ArgumentNullException(nameof(pointsRequiredToRemain), "Property is not nullable for class TierWillDowngradeData.");

            if (subledgerID.IsSet && subledgerID.Value == null)
                throw new ArgumentNullException(nameof(subledgerID), "Property is not nullable for class TierWillDowngradeData.");

            if (nextTier.IsSet && nextTier.Value == null)
                throw new ArgumentNullException(nameof(nextTier), "Property is not nullable for class TierWillDowngradeData.");

            if (tierExpirationDate.IsSet && tierExpirationDate.Value == null)
                throw new ArgumentNullException(nameof(tierExpirationDate), "Property is not nullable for class TierWillDowngradeData.");

            return new TierWillDowngradeData(customerProfileID.Value, loyaltyProgramID.Value.Value, currentTier.Value, currentPoints.Value.Value, pointsRequiredToRemain.Value.Value, subledgerID.Value, nextTier, tierExpirationDate);
        }

        /// <summary>
        /// Serializes a <see cref="TierWillDowngradeData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tierWillDowngradeData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TierWillDowngradeData tierWillDowngradeData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tierWillDowngradeData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TierWillDowngradeData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tierWillDowngradeData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TierWillDowngradeData tierWillDowngradeData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tierWillDowngradeData.CustomerProfileID == null)
                throw new ArgumentNullException(nameof(tierWillDowngradeData.CustomerProfileID), "Property is required for class TierWillDowngradeData.");

            if (tierWillDowngradeData.CurrentTier == null)
                throw new ArgumentNullException(nameof(tierWillDowngradeData.CurrentTier), "Property is required for class TierWillDowngradeData.");

            if (tierWillDowngradeData.SubledgerID == null)
                throw new ArgumentNullException(nameof(tierWillDowngradeData.SubledgerID), "Property is required for class TierWillDowngradeData.");

            if (tierWillDowngradeData.NextTierOption.IsSet && tierWillDowngradeData.NextTier == null)
                throw new ArgumentNullException(nameof(tierWillDowngradeData.NextTier), "Property is required for class TierWillDowngradeData.");

            writer.WriteString("CustomerProfileID", tierWillDowngradeData.CustomerProfileID);

            writer.WriteNumber("LoyaltyProgramID", tierWillDowngradeData.LoyaltyProgramID);

            writer.WriteString("CurrentTier", tierWillDowngradeData.CurrentTier);

            writer.WriteNumber("CurrentPoints", tierWillDowngradeData.CurrentPoints);

            writer.WriteNumber("PointsRequiredToRemain", tierWillDowngradeData.PointsRequiredToRemain);

            writer.WriteString("SubledgerID", tierWillDowngradeData.SubledgerID);

            if (tierWillDowngradeData.NextTierOption.IsSet)
                writer.WriteString("NextTier", tierWillDowngradeData.NextTier);

            if (tierWillDowngradeData.TierExpirationDateOption.IsSet)
                writer.WriteString("TierExpirationDate", tierWillDowngradeData.TierExpirationDateOption.Value.Value.ToString(TierExpirationDateFormat));
        }
    }
}
